--01
CREATE TABLE SYS_SEQUENCES
(
  UID           BINARY_INTEGER        NOT  NULL,
  ID            BINARY_INTEGER        NOT  NULL,
  NAME          VARCHAR(64)           NOT  NULL,
  MINVAL        BINARY_BIGINT,
  MAXVAL        BINARY_BIGINT,
  STEP          BINARY_BIGINT,
  CACHESIZE     BINARY_BIGINT,
  CYCLE_FLAG    BINARY_INTEGER,
  ORDER_FLAG    BINARY_INTEGER,
  ORG_SCN       BINARY_BIGINT,
  CHG_SCN       BINARY_BIGINT,
  LAST_NUMBER   BINARY_BIGINT
)SYSTEM 4 TABLESPACE SYSTEM
/

CREATE INDEX IX_SEQ$001 ON SYS_SEQUENCES(UID, NAME) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_SEQUENCES
/

--01
CREATE TABLE SYS_LOBS
(
  USER#         BINARY_INTEGER       NOT   NULL,
  TABLE#        BINARY_INTEGER       NOT   NULL,
  COLUMN#       BINARY_INTEGER       NOT   NULL,
  SPACE#        BINARY_INTEGER       NOT   NULL,
  ENTRY         BINARY_BIGINT,
  ORG_SCN       BINARY_BIGINT,
  CHG_SCN       BINARY_BIGINT,
  CHUNK         BINARY_INTEGER,
  PCTVERSION    BINARY_INTEGER,
  RETENSION     BINARY_INTEGER,
  FLAGS         BINARY_INTEGER
)SYSTEM 5 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_LOB$001 ON SYS_LOBS(USER#, TABLE#, COLUMN#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_LOBS
/

--01
CREATE TABLE SYS_RECYCLEBIN
(
  ID                BINARY_BIGINT        NOT   NULL,
  NAME              VARCHAR(30)          NOT   NULL,
  USER#             BINARY_INTEGER       NOT   NULL,
  ORG_NAME          VARCHAR(64)          NOT   NULL,
  PARTITION_NAME    VARCHAR(64),
  TYPE#             BINARY_INTEGER       NOT   NULL,
  OPERATION#        BINARY_INTEGER       NOT   NULL,
  SPACE#            BINARY_INTEGER       NOT   NULL,
  ENTRY             BINARY_BIGINT,
  FLAGS             BINARY_INTEGER       NOT   NULL,
  ORG_SCN           BINARY_BIGINT        NOT   NULL,
  REC_SCN           BINARY_BIGINT        NOT   NULL, 
  TCHG_SCN          BINARY_BIGINT,
  BASE_ID           BINARY_BIGINT        NOT   NULL,
  PURGE_ID          BINARY_BIGINT        NOT   NULL
) SYSTEM 6 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_RB$001 ON SYS_RECYCLEBIN(ID) TABLESPACE SYSTEM
/
CREATE INDEX IX_RB$002 ON SYS_RECYCLEBIN(BASE_ID, PURGE_ID) TABLESPACE SYSTEM
/
CREATE INDEX IX_RB$003 ON SYS_RECYCLEBIN(SPACE#) TABLESPACE SYSTEM
/
CREATE INDEX IX_RB$004 ON SYS_RECYCLEBIN(USER#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_RECYCLEBIN
/

--01
CREATE TABLE SYS_CONSTRAINT_DEFS
(
  USER#        BINARY_INTEGER        NOT  NULL,
  TABLE#       BINARY_INTEGER        NOT  NULL,
  CONS_NAME    VARCHAR(64)           NOT  NULL,
  CONS_TYPE    BINARY_INTEGER        NOT  NULL,
  COLS         BINARY_INTEGER,
  COL_LIST     VARCHAR(128),
  IND#		   BINARY_INTEGER,
  REF_USER#    BINARY_INTEGER,
  REF_TABLE#   BINARY_INTEGER,
  REF_CONS     BINARY_INTEGER,
  COND_TEXT    VARCHAR(2048),
  COND_DATA    BINARY(4096),
  FLAGS        BINARY_INTEGER,
  REFACT	   BINARY_INTEGER
) SYSTEM 7 TABLESPACE SYSTEM
/

CREATE INDEX IX_CONSDEF$001 ON SYS_CONSTRAINT_DEFS(USER#, TABLE#) TABLESPACE SYSTEM
/
CREATE INDEX IX_CONSDEF$002 ON SYS_CONSTRAINT_DEFS(REF_USER#, REF_TABLE#) TABLESPACE SYSTEM
/
CREATE UNIQUE INDEX IX_CONSDEF$003 ON SYS_CONSTRAINT_DEFS(USER#, CONS_NAME) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_CONSTRAINT_DEFS
/

--01
CREATE TABLE SYS_VIEWS
(
  USER#         BINARY_INTEGER         NOT  NULL,
  ID            BINARY_INTEGER         NOT  NULL,
  NAME          VARCHAR(64)            NOT  NULL,
  COLS          BINARY_INTEGER         NOT  NULL,
  FLAGS         BINARY_INTEGER         NOT  NULL,
  ORG_SCN       BINARY_BIGINT,
  CHG_SCN       BINARY_BIGINT,
  TEXT_LENGTH   BINARY_INTEGER         NOT  NULL,
  TEXT          CLOB                   NOT  NULL,
  SQL_TYPE      BINARY_INTEGER         NOT  NULL,
  OBJ#          BINARY_INTEGER         NOT  NULL
) SYSTEM 8 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_VIEW$001 ON SYS_VIEWS(USER#, NAME) TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_VIEW$002 ON SYS_VIEWS(USER#, ID) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_VIEWS
/

--01
CREATE TABLE SYS_VIEW_COLS
(
  USER#          BINARY_INTEGER         NOT NULL,
  VIEW#          BINARY_INTEGER         NOT NULL,
  ID             BINARY_INTEGER         NOT NULL,
  NAME           VARCHAR2(128)          NOT NULL,
  DATATYPE       BINARY_INTEGER         NOT NULL,
  BYTES          BINARY_INTEGER         NOT NULL,
  PRECISION      BINARY_INTEGER,
  SCALE          BINARY_INTEGER,
  NULLABLE       BINARY_INTEGER,
  FLAGS          BINARY_INTEGER
)SYSTEM 9  TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_VIEWCOL$001 ON SYS_VIEW_COLS(USER#, VIEW#, ID) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR  SYS_VIEW_COLS
/

--01
CREATE TABLE SYS_DUMMY
(
  DUMMY          VARCHAR(1)     NOT NULL
) SYSTEM 10 TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_DUMMY
/

--01
CREATE TABLE SYS_PROCS 
(
  USER#           BINARY_INTEGER       NOT NULL,
  OBJ#            BINARY_BIGINT        NOT NULL,
  NAME            VARCHAR(128)         NOT NULL,
  CLASS           BINARY_INTEGER       NOT NULL,
  TYPE            CHAR                 NOT NULL,
  SOURCE          CLOB                 NOT NULL,
  AGGREGATE       BINARY_INTEGER       NOT NULL,
  PIPELINED       BINARY_INTEGER       NOT NULL,
  TRIG_TABLE_USER VARCHAR(128),
  TRIG_TABLE      VARCHAR(128),
  ORG_SCN         BINARY_BIGINT        NOT NULL,
  CHG_SCN         BINARY_BIGINT        NOT NULL,
  TRIG_STATUS     VARCHAR(16),
  STATUS          BINARY_INTEGER       NOT NULL
) SYSTEM 11 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_PROC_001 ON SYS_PROCS(NAME, USER#, CLASS) TABLESPACE SYSTEM
/

CREATE INDEX IX_PROC_002 ON SYS_PROCS(TRIG_TABLE, TRIG_TABLE_USER) TABLESPACE SYSTEM
/

CREATE INDEX IX_PROC_003 ON SYS_PROCS(USER#, OBJ#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR  SYS_PROCS
/

--01
CREATE SEQUENCE SEQ_PROC_001 START WITH 30000 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE
/

--01
CREATE TABLE SYS_EXTERNAL_TABLES
(
  TABLE#        BINARY_INTEGER    NOT NULL,
  TYPE          BINARY_INTEGER    NOT NULL,
  DIRECTORY     VARCHAR(256)      NOT NULL,
  LOCATION      VARCHAR(30)       NOT NULL,
  RECORDS_DEL   VARCHAR(1)        NOT NULL,
  FIELDS_DEL    VARCHAR(1)        NOT NULL
) SYSTEM 12 TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_EXTERNAL_TABLES
/

--01
CREATE TABLE SYS_PENDING_TRANS
(
  GLOBAL_TRAN_ID  VARCHAR(256)    NOT NULL,
  LOCAL_TRAN_ID   BINARY_BIGINT,
  TLOCK_LOBS      BINARY(4000),
  TLOCK_LOBS_EXT  BLOB,
  FORMAT_ID       BINARY_BIGINT,
  BRANCH_ID       VARCHAR(128),
  OWNER           BINARY_INTEGER
) SYSTEM 13 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_PENDINGTRANS_001 ON SYS_PENDING_TRANS(GLOBAL_TRAN_ID, FORMAT_ID, BRANCH_ID) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_PENDING_TRANS
/

--01
CREATE TABLE SYS_SYNONYMS
(
  USER#            BINARY_INTEGER     NOT  NULL,
  ID               BINARY_INTEGER     NOT  NULL,
  ORG_SCN          BINARY_BIGINT,
  CHG_SCN          BINARY_BIGINT,
  SYNONYM_NAME     VARCHAR2(64)       NOT  NULL,
  TABLE_OWNER      VARCHAR2(64),      
  TABLE_NAME       VARCHAR2(64)       NOT  NULL,
  FLAGS            BINARY_INTEGER     NOT  NULL,
  TYPE             BINARY_INTEGER DEFAULT 0 NOT NULL
) SYSTEM 14 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_SYNONYM$001 ON SYS_SYNONYMS(USER#, SYNONYM_NAME) TABLESPACE SYSTEM
/

CREATE INDEX IX_SYNONYM$002 ON SYS_SYNONYMS(USER#, ID) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_SYNONYMS
/

--01
CREATE TABLE SYS_COMMENTS
(
  USER#         BINARY_INTEGER       NOT  NULL,
  TABLE#        BINARY_INTEGER       NOT  NULL,
  COLUMN#       BINARY_INTEGER,
  TEXT          VARCHAR2(4000)
) SYSTEM 15 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_COMMENT$001 ON SYS_COMMENTS(USER#, TABLE#, COLUMN#) TABLESPACE SYSTEM
/


ALTER SYSTEM LOAD DICTIONARY FOR SYS_COMMENTS
/

--01
CREATE TABLE SYS_PRIVS
(
  GRANTEE_ID    BINARY_INTEGER NOT NULL,
  GRANTEE_TYPE  BINARY_INTEGER NOT NULL,
  PRIVILEGE     BINARY_INTEGER NOT NULL,
  ADMIN_OPTION  BINARY_INTEGER NOT NULL
) SYSTEM 16 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_SYS_PRIVS$_001 ON SYS_PRIVS(GRANTEE_ID, GRANTEE_TYPE, PRIVILEGE)
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_PRIVS
/

--01
CREATE TABLE SYS_OBJECT_PRIVS
(
  GRANTEE       BINARY_INTEGER NOT NULL,
  GRANTEE_TYPE  BINARY_INTEGER NOT NULL,
  OBJECT_OWNER  BINARY_INTEGER NOT NULL,
  OBJECT_NAME   VARCHAR(64)    NOT NULL,
  OBJECT_TYPE   BINARY_INTEGER NOT NULL,
  PRIVILEGE     BINARY_INTEGER NOT NULL,
  GRANTABLE     BINARY_INTEGER NOT NULL,
  GRANTOR       BINARY_INTEGER NOT NULL
) SYSTEM 17 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_OBJECT_PRIVS$_001 ON SYS_OBJECT_PRIVS(GRANTEE, GRANTEE_TYPE, OBJECT_OWNER, OBJECT_NAME, OBJECT_TYPE, PRIVILEGE)
/

CREATE INDEX IX_OBJECT_PRIVS$_002 ON SYS_OBJECT_PRIVS(OBJECT_OWNER, OBJECT_NAME, OBJECT_TYPE)
/

CREATE INDEX IX_OBJECT_PRIVS$_003 ON SYS_OBJECT_PRIVS(GRANTOR)
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_OBJECT_PRIVS
/

--01
CREATE TABLE SYS_USER_ROLES
(
  GRANTEE_ID        BINARY_INTEGER NOT NULL,
  GRANTEE_TYPE      BINARY_INTEGER NOT NULL,
  GRANTED_ROLE_ID   BINARY_INTEGER NOT NULL,
  ADMIN_OPTION      BINARY_INTEGER NOT NULL,
  DEFAULT_ROLE      BINARY_INTEGER
) SYSTEM 18 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_USER_ROLES$_001 ON SYS_USER_ROLES(GRANTEE_ID, GRANTEE_TYPE, GRANTED_ROLE_ID)
/

CREATE INDEX IX_USER_ROLES$_002 ON SYS_USER_ROLES(GRANTED_ROLE_ID)
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_USER_ROLES
/

--01
CREATE TABLE SYS_ROLES
(
  ID          BINARY_INTEGER NOT NULL,
  OWNER_UID   BINARY_INTEGER NOT NULL,
  NAME        VARCHAR(64)    NOT NULL,
  PASSWORD    VARCHAR(256)
) SYSTEM 19 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_ROLES$_001 ON SYS_ROLES(ID, NAME)
/

CREATE INDEX IX_ROLES$_002 ON SYS_ROLES(OWNER_UID)
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_ROLES
/

--01
CREATE TABLE SYS_HISTGRAM
(
  USER#         BINARY_INTEGER,
  TABLE#        BINARY_INTEGER,
  COL#          BINARY_INTEGER,
  BUCKET        VARCHAR(4000),
  ENDPOINT      BINARY_INTEGER,
  PART#         BINARY_INTEGER,
  EPVALUE       VARCHAR(1000),
  SPARE1        BINARY_BIGINT,
  SPARE2        BINARY_BIGINT,
  SPARE3        BINARY_BIGINT
) SYSTEM 20 TABLESPACE SYSTEM
/

CREATE INDEX IX_HIST_003 ON SYS_HISTGRAM(USER#,TABLE#,COL#,PART#,ENDPOINT)
/

ALTER SYSTEM LOAD DICTIONARY FOR  SYS_HISTGRAM
/

--01
CREATE TABLE SYS_HISTGRAM_ABSTR
(
  USER#         BINARY_INTEGER,
  TAB#          BINARY_INTEGER,
  COL#          BINARY_INTEGER,
  BUCKET_NUM    BINARY_INTEGER,
  ROW_NUM       BINARY_INTEGER,
  NULL_NUM      BINARY_INTEGER,
  ANALYZE_TIME  DATE,
  MINVALUE      VARCHAR(4000),
  MAXVALUE      VARCHAR(4000),
  DIST_NUM      BINARY_INTEGER,
  DENSITY       BINARY_DOUBLE,
  SPARE1        BINARY_BIGINT,
  SPARE2        BINARY_BIGINT,
  SPARE3        BINARY_BIGINT,
  SPARE4        BINARY_BIGINT
) SYSTEM 21 TABLESPACE SYSTEM
/

CREATE INDEX IX_HIST_HEAD_002 ON SYS_HISTGRAM_ABSTR(ANALYZE_TIME)
/

CREATE UNIQUE INDEX IX_HIST_HEAD_003 ON SYS_HISTGRAM_ABSTR(USER#,TAB#,COL#,SPARE1)
/

ALTER SYSTEM LOAD DICTIONARY FOR  SYS_HISTGRAM_ABSTR
/
--01
CREATE TABLE SYS_PART_OBJECTS
(
  USER#             BINARY_INTEGER       NOT   NULL,
  TABLE#            BINARY_INTEGER       NOT   NULL,
  INDEX#            BINARY_INTEGER       NOT   NULL,
  PARTTYPE          BINARY_INTEGER       NOT   NULL,
  PARTCNT#          BINARY_INTEGER       NOT   NULL,
  PARTKEYS#         BINARY_INTEGER       NOT   NULL,
  FLAGS             BINARY_INTEGER       NOT   NULL,
  INTERVAL          VARCHAR(1000),
  BINTERVAL         BINARY(200)
) SYSTEM 22 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_PARTOBJECT$001 ON SYS_PART_OBJECTS(USER#, TABLE#, INDEX#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_PART_OBJECTS
/

--01
CREATE TABLE SYS_PART_COLUMNS
(
  USER#         BINARY_INTEGER       NOT   NULL,
  TABLE#        BINARY_INTEGER       NOT   NULL,
  COLUMN#       BINARY_INTEGER       NOT   NULL,
  POSITION#     BINARY_INTEGER       NOT   NULL,
  DATATYPE      BINARY_INTEGER       NOT   NULL
) SYSTEM 23 TABLESPACE SYSTEM
/

CREATE INDEX IX_PARTCOLUMN$001 ON SYS_PART_COLUMNS(USER#, TABLE#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_PART_COLUMNS
/

--01
CREATE TABLE SYS_TABLE_PARTS
(
  USER#         BINARY_INTEGER       NOT   NULL,
  TABLE#        BINARY_INTEGER       NOT   NULL,
  PART#         BINARY_INTEGER       NOT   NULL,
  NAME          VARCHAR(64)          NOT   NULL,
  HIBOUNDLEN    BINARY_INTEGER       NOT   NULL,
  HIBOUNDVAL    VARCHAR(4000),
  SPACE#        BINARY_INTEGER       NOT   NULL,
  ORG_SCN       BINARY_BIGINT        NOT   NULL,
  ENTRY         BINARY_BIGINT        NOT   NULL,
  INITRANS      BINARY_INTEGER       NOT   NULL,
  PCTFREE       BINARY_INTEGER       NOT   NULL,
  FLAGS         BINARY_INTEGER       NOT   NULL,
  BHIBOUNDVAL   BINARY(4000),
  ROWCNT        BINARY_INTEGER,
  BLKCNT        BINARY_INTEGER,
  EMPCNT        BINARY_INTEGER,
  AVGRLN        BINARY_INTEGER,
  SAMPLESIZE    BINARY_INTEGER,
  ANALYZETIME   DATE
) SYSTEM 24 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_TABLEPART$001 ON SYS_TABLE_PARTS(USER#, TABLE#, PART#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_TABLE_PARTS
/

--01
CREATE TABLE SYS_INDEX_PARTS
(
  USER#         BINARY_INTEGER       NOT   NULL,
  TABLE#        BINARY_INTEGER       NOT   NULL,
  INDEX#        BINARY_INTEGER       NOT   NULL,
  PART#         BINARY_INTEGER       NOT   NULL,
  NAME          VARCHAR(64)          NOT   NULL,
  HIBOUNDLEN    BINARY_INTEGER       NOT   NULL,
  HIBOUNDVAL    VARCHAR(4000),
  SPACE#        BINARY_INTEGER       NOT   NULL,
  ORG_SCN       BINARY_BIGINT        NOT   NULL,
  ENTRY         BINARY_BIGINT        NOT   NULL,
  INITRANS      BINARY_INTEGER       NOT   NULL,
  PCTFREE       BINARY_INTEGER       NOT   NULL,
  FLAGS         BINARY_INTEGER       NOT   NULL,
  BHIBOUNDVAL   BINARY(4000),
  BLEVEL        BINARY_INTEGER,
  LEVEL_BLOCKS  BINARY_INTEGER,
  DISTKEY       BINARY_INTEGER,
  LBLKKEY       BINARY_DOUBLE,
  DBLKKEY       BINARY_DOUBLE,
  ANALYZETIME   DATE,
  EMPTY_LEAF_BLOCKS BINARY_INTEGER,
  CLUFAC        BINARY_INTEGER,
  SAMPLESIZE    BINARY_INTEGER,
  COMB_COLS_2_NDV BINARY_INTEGER,
  COMB_COLS_3_NDV BINARY_INTEGER,
  COMB_COLS_4_NDV BINARY_INTEGER
) SYSTEM 25 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_INDEXPART$001 ON SYS_INDEX_PARTS(USER#, TABLE#, INDEX#, PART#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_INDEX_PARTS
/

--01
CREATE TABLE SYS_LOB_PARTS
(
  USER#         BINARY_INTEGER       NOT   NULL,
  TABLE#        BINARY_INTEGER       NOT   NULL,
  COLUMN#       BINARY_INTEGER       NOT   NULL,
  PART#         BINARY_INTEGER       NOT   NULL,
  SPACE#        BINARY_INTEGER       NOT   NULL,
  ORG_SCN       BINARY_BIGINT        NOT   NULL,
  ENTRY         BINARY_BIGINT        NOT   NULL,
  FLAGS         BINARY_INTEGER       NOT   NULL
) SYSTEM 26 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_LOBPART$001 ON SYS_LOB_PARTS(USER#, TABLE#, COLUMN#, PART#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_LOB_PARTS
/

--01
CREATE TABLE SYS_SHADOW_INDEXES
(
  USER#         BINARY_INTEGER          NOT NULL,
  TABLE#        BINARY_INTEGER          NOT NULL,
  ID            BINARY_INTEGER          NOT NULL,
  NAME          VARCHAR(64)             NOT NULL,
  SPACE#        BINARY_INTEGER          NOT NULL,
  SEQUENCE#     BINARY_BIGINT           NOT NULL,
  ENTRY         BINARY_BIGINT           NOT NULL,
  IS_PRIMARY    BINARY_INTEGER          NOT NULL,
  IS_UNIQUE     BINARY_INTEGER          NOT NULL,
  TYPE          BINARY_INTEGER          NOT NULL,
  COLS          BINARY_INTEGER          NOT NULL,
  COL_LIST      VARCHAR(128)            NOT NULL,
  INITRANS      BINARY_INTEGER          NOT NULL,
  CR_MODE       BINARY_INTEGER          NOT NULL,
  FLAGS         BINARY_INTEGER          NOT NULL,
  PARTED        BINARY_INTEGER          NOT NULL,
  PCTFREE       BINARY_INTEGER          NOT NULL
) SYSTEM 27 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_SHADOW_INDEX$_001 ON SYS_SHADOW_INDEXES(USER#, TABLE#);
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_SHADOW_INDEXES
/

--01
CREATE TABLE SYS_PROFILE
(
  NAME           VARCHAR(64)          NOT NULL,
  PROFILE#       BINARY_INTEGER       NOT NULL,	
  RESOURCE#      BINARY_INTEGER       NOT NULL,         		
  THRESHOLD      BINARY_BIGINT        NOT NULL           
) SYSTEM 28 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_PROFILE$_001 ON SYS_PROFILE(PROFILE#, RESOURCE#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_PROFILE
/

--01
CREATE TABLE SYS_SHADOW_INDEX_PARTS
(
  USER#         BINARY_INTEGER       NOT   NULL,
  TABLE#        BINARY_INTEGER       NOT   NULL,
  INDEX#        BINARY_INTEGER       NOT   NULL,
  PART#         BINARY_INTEGER       NOT   NULL,
  NAME          VARCHAR(64)          NOT   NULL,
  HIBOUNDLEN    BINARY_INTEGER       NOT   NULL,
  HIBOUNDVAL    VARCHAR(4000),
  SPACE#        BINARY_INTEGER       NOT   NULL,
  ORG_SCN       BINARY_BIGINT        NOT   NULL,
  ENTRY         BINARY_BIGINT        NOT   NULL,
  INITRANS      BINARY_INTEGER       NOT   NULL,
  PCTFREE       BINARY_INTEGER       NOT   NULL,
  FLAGS         BINARY_INTEGER,
  BHIBOUNDVAL   BINARY(4000)
) SYSTEM 29 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_SHW_INDEXPART$001 ON SYS_SHADOW_INDEX_PARTS(USER#, TABLE#, INDEX#, PART#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_SHADOW_INDEX_PARTS
/

--01
CREATE TABLE SYS_BACKUP_SETS
(
  RECID                   BINARY_BIGINT     NOT NULL,
  TYPE                    BINARY_INTEGER    NOT NULL,
  STAGE                   BINARY_INTEGER    NOT NULL,
  STATUS                  BINARY_INTEGER    NOT NULL,
  INCREMENTAL_LEVEL       BINARY_INTEGER    NOT NULL,
  TAG                     VARCHAR(64)       NOT NULL,
  SCN                     BINARY_BIGINT     NOT NULL,
  LSN                     BINARY_BIGINT     NOT NULL,
  DEVICE_TYPE             BINARY_INTEGER    NOT NULL,
  BASE_TAG                VARCHAR(64)       NOT NULL,
  DIR                     VARCHAR(256)      NOT NULL,
  RESETLOGS               BINARY_INTEGER    NOT NULL,
  POLICY                  VARCHAR(128)      NOT NULL,
  RCY_ASN                 BINARY_INTEGER    NOT NULL,
  RCY_OFFSET              BINARY_BIGINT     NOT NULL,
  RCY_LFN                 BINARY_BIGINT     NOT NULL,
  LRP_ASN                 BINARY_INTEGER    NOT NULL,
  LRP_OFFSET              BINARY_BIGINT     NOT NULL,
  LRP_LFN                 BINARY_BIGINT     NOT NULL,
  START_TIME              TIMESTAMP         NOT NULL,
  COMPLETION_TIME         TIMESTAMP         NOT NULL
) SYSTEM 30 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_BACKUP_SET$001 ON SYS_BACKUP_SETS(RECID) TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_BACKUP_SET$002 ON SYS_BACKUP_SETS(TAG) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_BACKUP_SETS
/

--01
CREATE SEQUENCE OBJECT_ID$
MINVALUE 1000
NOCACHE
/

--01
CREATE TABLE SYS_DATA_NODES
(
  NODE_ID          BINARY_INTEGER    NOT NULL,
  NODE_NAME        VARCHAR(128)      NOT NULL,
  NODE_TYPE        VARCHAR(128)      NOT NULL, 
  NODE_HOST        VARCHAR(64)       NOT NULL,
  NODE_PORT        BINARY_INTEGER    NOT NULL,
  GROUP_ID         BINARY_INTEGER    NOT NULL,
  IS_PRIMARY       BINARY_INTEGER    ,
  WEIGHT           BINARY_INTEGER    ,
  NODE_USER        VARCHAR(128)      NOT NULL,
  NODE_PASSWORD    VARCHAR(512)      NOT NULL,
  MIN_CONN         BINARY_INTEGER    NOT NULL,
  MAX_CONN         BINARY_INTEGER    NOT NULL
) SYSTEM 31 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_DATA_NODES_ID$001 ON SYS_DATA_NODES(NODE_ID) TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_DATA_NODES_NAME$002 ON SYS_DATA_NODES(NODE_NAME) TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_DATA_NODES_HOST$003 ON SYS_DATA_NODES(NODE_HOST, NODE_PORT) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_DATA_NODES
/

--01
CREATE TABLE SYS_PENDING_DIST_TRANS
(
  GLOBAL_TRAN_ID   VARCHAR(256)       NOT NULL,
  TRAN_COMMIT_TIME TIMESTAMP          NOT NULL,
  TRX_STATUS       BINARY_INTEGER     NOT NULL,
  NEED_CLEAN       BINARY_INTEGER     NOT NULL
) SYSTEM 32 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_PENDIN_DISGTRANS_001 ON SYS_PENDING_DIST_TRANS(GLOBAL_TRAN_ID) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_PENDING_DIST_TRANS
/

--01
CREATE TABLE SYS_DISTRIBUTE_STRATEGIES
(
  USER#            BINARY_INTEGER     NOT NULL,
  TABLE#           BINARY_INTEGER     NOT NULL,
  DIST_DATA        VARCHAR(1024)      NOT NULL,
  BUCKETS          BLOB
) SYSTEM 33 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_DISTRIBUTE_STRATEGY$001 ON SYS_DISTRIBUTE_STRATEGIES(USER#, TABLE#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_DISTRIBUTE_STRATEGIES
/

--01
CREATE TABLE SYS_GARBAGE_SEGMENTS
(
  UID            BINARY_INTEGER,
  OID            BINARY_INTEGER,
  INDEX_ID       BINARY_INTEGER,
  COLUMN_ID      BINARY_INTEGER,
  SPACE          BINARY_INTEGER,
  ENTRY          BINARY_BIGINT,
  ORG_SCN        BINARY_BIGINT,
  SEG_SCN        BINARY_BIGINT,
  INITRANS       BINARY_INTEGER,
  PCTFREE        BINARY_INTEGER,
  OP_TYPE        BINARY_INTEGER,
  REUSE          BINARY_INTEGER,
  SERIAL         BINARY_BIGINT,
  SPARE2         BINARY_INTEGER,
  SPARE3         BINARY_INTEGER
) SYSTEM 34 TABLESPACE SYSTEM
/

CREATE INDEX IX_GARBAGE_SEGMENT$001 ON SYS_GARBAGE_SEGMENTS(UID, OID) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_GARBAGE_SEGMENTS
/

--01
CREATE TABLE SYS_PART_STORES
(
  USER#             BINARY_INTEGER       NOT   NULL,
  TABLE#            BINARY_INTEGER       NOT   NULL,
  INDEX#            BINARY_INTEGER       NOT   NULL,
  POSITION#         BINARY_INTEGER       NOT   NULL,
  SPACE#            BINARY_INTEGER       NOT   NULL
) SYSTEM 35 TABLESPACE SYSTEM
/

CREATE INDEX IX_PARTSTORE$001 ON SYS_PART_STORES(USER#, TABLE#, INDEX#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_PART_STORES
/

--01
CREATE TABLE SYS_USER_HISTORY
(
  USER#                   BINARY_INTEGER        NOT NULL,
  PASSWORD                BINARY(512),
  PASSWORD_DATE           DATE     
) SYSTEM 36 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_USER_HISTORY$001 ON SYS_USER_HISTORY(USER#, PASSWORD_DATE) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_USER_HISTORY
/

--01
CREATE TABLE SYS_PROC_ARGS 
(
  USER#           BINARY_INTEGER      NOT NULL,
  OBJECT_NAME     VARCHAR(128)        NOT NULL,
  ARGUMENT_NAME   VARCHAR(128),
  POSITION        BINARY_INTEGER      NOT NULL,
  SEQUENCE        BINARY_INTEGER      NOT NULL,
  DATA_LEVEL      BINARY_INTEGER      NOT NULL,
  DATA_TYPE       BINARY_INTEGER      NOT NULL,
  DEFAULTED       BINARY_INTEGER      NOT NULL,
  DEFAULT_VALUE   VARCHAR(128),
  DEFAULT_LENGTH  VARCHAR(128),
  IN_OUT          BINARY_INTEGER       NOT NULL,
  DATA_LENGTH     BINARY_INTEGER,
  DATA_PRECISION  BINARY_INTEGER,
  DATA_SCALE      BINARY_INTEGER,
  TYPE#           BINARY_BIGINT,
  RESERVERD       VARCHAR(128),
  PACKAGE         VARCHAR(128),
  PROC_SEQ        BINARY_INTEGER   DEFAULT 1  NOT NULL,
  OVERLOAD        BINARY_INTEGER   DEFAULT 0  NOT NULL,
  RESERVERD1      BINARY_INTEGER,
  RESERVERD2      BINARY_INTEGER,
  RESERVERD3      VARCHAR(128),
  RESERVERD4      VARCHAR(128),
  RESERVERD5      VARCHAR(128)
) SYSTEM 37 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_PROCARGU_001 ON SYS_PROC_ARGS(USER#, OBJECT_NAME, PACKAGE, SEQUENCE, OVERLOAD) TABLESPACE SYSTEM
/

CREATE INDEX IX_PROCARGU_002 ON SYS_PROC_ARGS(USER#, PACKAGE) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR  SYS_PROC_ARGS
/

--01
CREATE TABLE SYS_LOGIC_REPL
(
  USER# 	BINARY_INTEGER	NOT NULL,
  TABLE#	BINARY_INTEGER	NOT NULL,
  STATUS	BINARY_INTEGER	NOT NULL,
  INDEX#	BINARY_INTEGER
) SYSTEM 38 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_LOGICREP$_001 ON SYS_LOGIC_REPL(USER#, TABLE#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_LOGIC_REPL
/

--01
CREATE TABLE SYS_DML_STATS
(
  USER#         BINARY_INTEGER       NOT   NULL,
  TABLE#        BINARY_INTEGER       NOT   NULL,
  INSERTS       BINARY_INTEGER       NOT   NULL,
  UPDATES       BINARY_INTEGER       NOT   NULL,
  DELETES       BINARY_INTEGER       NOT   NULL,
  MODIFY_TIME   TIMESTAMP            NOT   NULL,
  FLAGS         BINARY_INTEGER       NOT   NULL,
  DROP_SEGMENTS BINARY_INTEGER       NOT   NULL,
  PARTED        BINARY_INTEGER,
  PART#         BINARY_INTEGER
) SYSTEM 39 TABLESPACE SYSTEM
/

CREATE INDEX IX_MODS_001 ON SYS_DML_STATS(USER#, TABLE#) TABLESPACE SYSTEM
/

CREATE INDEX IX_MODS_002 ON SYS_DML_STATS(MODIFY_TIME) TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_MODS_003 ON SYS_DML_STATS(USER#, TABLE#, PART#) TABLESPACE SYSTEM
/
ALTER SYSTEM LOAD DICTIONARY FOR  SYS_DML_STATS
/

--01
CREATE TABLE SYS_DEPENDENCIES 
(
D_OWNER#    BINARY_INTEGER     NOT NULL,             
D_OBJ#      BINARY_BIGINT      NOT NULL,          
D_TYPE#     BINARY_INTEGER     NOT NULL,                    
D_SCN       BINARY_BIGINT      NOT NULL,        
ORDER#      BINARY_INTEGER     NOT NULL,                    
P_OWNER#    BINARY_INTEGER     NOT NULL,                 
P_OBJ#      BINARY_BIGINT      NOT NULL,            
P_TYPE#     BINARY_INTEGER     NOT NULL,                   
P_SCN       BINARY_BIGINT      NOT NULL,              
D_NAME      VARCHAR(64)                ,            
P_NAME      VARCHAR(64)                   
) SYSTEM 40 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_DEPENDENCY1 ON SYS_DEPENDENCIES (D_OWNER#,D_OBJ#, D_TYPE#, ORDER#) TABLESPACE SYSTEM
/

CREATE INDEX IX_DEPENDENCY2 ON SYS_DEPENDENCIES (P_OWNER#,P_OBJ#, P_TYPE#) TABLESPACE SYSTEM
/

CREATE INDEX IX_DEPENDENCY3 ON SYS_DEPENDENCIES (D_NAME) TABLESPACE SYSTEM
/

CREATE INDEX IX_DEPENDENCY4 ON SYS_DEPENDENCIES (P_NAME) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR  SYS_DEPENDENCIES
/

--01
CREATE TABLE SYS_LINKS 
(
  OWNER#          INTEGER       NOT NULL,
  NAME            VARCHAR2(128) NOT NULL,
  CTIME           DATE          NOT NULL,
  NODE_ID         INTEGER       NOT NULL,
  HOST            VARCHAR2(2000),
  USERID          VARCHAR2(64),
  PASSWORD        VARCHAR2(512)
) SYSTEM 42 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_LINK$001 ON SYS_LINKS(OWNER#, NAME) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_LINKS
/

--01
CREATE TABLE SYS_DISTRIBUTE_RULES
(
  UID           INTEGER        NOT  NULL,
  ID            INTEGER        NOT  NULL,
  DIST_DATA     VARCHAR(1024)  NOT  NULL,
  BUCKETS       BLOB,
  NAME          VARCHAR(64)    NOT  NULL,
  ORG_SCN       BIGINT,
  CHG_SCN       BIGINT,
  COLUMNS       VARCHAR(1024),
  COLUMN_COUNT  INTEGER        NOT  NULL
)SYSTEM 41 TABLESPACE SYSTEM
/

CREATE INDEX IX_DISTRIBUTE_RULE$001 ON SYS_DISTRIBUTE_RULES(NAME) TABLESPACE SYSTEM
/

CREATE INDEX IX_DISTRIBUTE_RULE$002 ON SYS_DISTRIBUTE_RULES(ID) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_DISTRIBUTE_RULES
/

--01
CREATE ROLE DBA
/

GRANT ALL PRIVILEGES TO DBA WITH ADMIN OPTION
/

--01
CREATE ROLE RESOURCE
/

GRANT CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE, CREATE TABLE TO RESOURCE
/

--01
CREATE GLOBAL TEMPORARY TABLE SYS_TMP_SEG_STATS
(
ORG_SCN             	 BINARY_BIGINT   PRIMARY KEY,
UID                      BINARY_INTEGER,
OID                      BINARY_INTEGER,
LOGIC_READS       	 BINARY_BIGINT,
PHYSICAL_WRITES          BINARY_BIGINT,
PHYSICAL_READS           BINARY_BIGINT,
ITL_WAITS                 BINARY_BIGINT,
BUF_BUSY_WAITS            BINARY_BIGINT,
ROW_LOCK_WAITS            BINARY_BIGINT
)SYSTEM 43 ON COMMIT PRESERVE ROWS
/
CREATE INDEX IDX_OBJECT ON SYS_TMP_SEG_STATS(UID, OID)
/
ALTER SYSTEM LOAD DICTIONARY FOR  SYS_TMP_SEG_STATS
/
--01
CREATE GLOBAL TEMPORARY TABLE EXP_TAB_RELATIONS
(
  TBL_NAME     VARCHAR(64),
  TBL_PARENT   VARCHAR(64)
) ON COMMIT PRESERVE ROWS
/
ALTER SYSTEM LOAD DICTIONARY FOR  EXP_TAB_RELATIONS
/

--01
CREATE GLOBAL TEMPORARY TABLE EXP_TAB_ORDERS
(
  TBL_NAME     VARCHAR(64),
  TBL_LEVEL    BINARY_INTEGER
) ON COMMIT PRESERVE ROWS
/
ALTER SYSTEM LOAD DICTIONARY FOR  EXP_TAB_ORDERS
/

--01
CREATE TABLE SYS_JOBS
(
  JOB             BINARY_BIGINT NOT NULL,
  LOWNER          VARCHAR(64) NOT NULL,
  POWNER          VARCHAR(64) NOT NULL,
  COWNER          VARCHAR(64) NOT NULL,
  LAST_DATE       DATE,
  THIS_DATE       DATE,
  NEXT_DATE       DATE NOT NULL,
  TOTAL           BINARY_INTEGER DEFAULT 0 NOT NULL,
  INTERVAL#       VARCHAR(200) NOT NULL,
  FAILURES        BINARY_INTEGER DEFAULT 0 NOT NULL,
  BROKEN          BINARY_INTEGER DEFAULT 0 NOT NULL,
  WHAT            VARCHAR(4000) NOT NULL,
  CREATE_DATE     DATE NOT NULL,  
  INSTANCE        BINARY_INTEGER DEFAULT 0 NOT NULL
)SYSTEM 45 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX SYS.I_JOB_1 ON SYS.SYS_JOBS (JOB)  TABLESPACE SYSTEM
/
CREATE INDEX SYS.I_JOB_2 ON SYS.SYS_JOBS (NEXT_DATE) TABLESPACE SYSTEM
/
ALTER SYSTEM LOAD DICTIONARY FOR SYS_JOBS
/

--01
CREATE SEQUENCE SYS.JOBSEQ MINVALUE 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE
/

--01
CREATE TABLE SYS_SQL_MAPS
(
  SRC_HASHCODE BINARY_INTEGER NOT NULL,
  SRC_TEXT CLOB NOT NULL,
  DST_TEXT CLOB NOT NULL,
  USER#    BINARY_INTEGER NOT NULL
)SYSTEM 46 TABLESPACE SYSTEM
/

CREATE INDEX IDX_SQL_MAP_001 ON SYS_SQL_MAPS(SRC_HASHCODE)
/
CREATE INDEX IDX_SQL_MAP_002 ON SYS_SQL_MAPS(USER#)
/
ALTER SYSTEM LOAD DICTIONARY FOR SYS_SQL_MAPS
/

--01
CREATE TABLE SYS_SYNC_INFO
(
  SYNC_TIME       BINARY_BIGINT
)SYSTEM 47 TABLESPACE SYSTEM
/
ALTER SYSTEM LOAD DICTIONARY FOR SYS_SYNC_INFO
/
--01
CREATE TABLE SYS_DIST_DDL_LOGINFO
(
  DIST_DDL_ID      VARCHAR(256)       NOT NULL,
  GROUP_ID         BINARY_INTEGER     NOT NULL,
  DATANODE_ID      BINARY_INTEGER     NOT NULL,
  DDL              CLOB               NOT NULL,
  CREATE_TIME  		 TIMESTAMP          NOT NULL,
  EXPIRED_TIME  	 TIMESTAMP          NOT NULL,
  RETRY_TIMES      BINARY_INTEGER     NOT NULL,
  STATUS           BINARY_INTEGER     NOT NULL
) SYSTEM 48 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_DIST_DDL_LOGINFO_001 ON SYS_DIST_DDL_LOGINFO(DIST_DDL_ID) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_DIST_DDL_LOGINFO
/