CREATE TABLE SYS_TABLEMETA_DIFF
(
    OBJECT_SCN          BINARY_BIGINT       NOT NULL,
    USER_NAME           VARCHAR(64 BYTE)    NOT NULL,
    OBJECT_NAME         VARCHAR(64 BYTE)    NOT NULL,
    USER_ID             BINARY_INTEGER      NOT NULL,
    TABLE_ID            BINARY_INTEGER      NOT NULL,
    OBJECT_ID           BINARY_INTEGER      NOT NULL,
    OBJECT_VERSION      BINARY_BIGINT       NOT NULL,
    DDL_TYPE            VARCHAR(64 BYTE)    NOT NULL,
    CHG_SCN             BINARY_BIGINT       NOT NULL,
    INVALID_SCN         BINARY_BIGINT       NOT NULL,
    OPTIONS             RAW(128),
    CONSTRAINT "PK_SYS_TABLEMETA_DIFF" PRIMARY KEY("OBJECT_SCN", "OBJECT_VERSION", "CHG_SCN")
) SYSTEM 1045 TABLESPACE SYSAUX
/

CREATE INDEX IX_DIC_DIFF ON SYS_TABLEMETA_DIFF (USER_ID, TABLE_ID)
TABLESPACE SYSAUX
/

CREATE INDEX IX_DEL_DIFF ON SYS_TABLEMETA_DIFF (OBJECT_SCN, OBJECT_VERSION, CHG_SCN, INVALID_SCN)
TABLESPACE SYSAUX
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_TABLEMETA_DIFF
/
