CREATE TABLE SYS_COLUMNMETA_HIS
(
    OBJECT_SCN          BINARY_BIGINT       NOT NULL,
    OBJECT_VERSION      BINARY_BIGINT       NOT NULL,
    USER_ID             BINARY_INTEGER      NOT NULL,
    TABLE_ID            BINARY_INTEGER      NOT NULL,
    OBJECT_ID           BINARY_INTEGER      NOT NULL,
    COLUMN_ID           BINARY_INTEGER      NOT NULL,
    COLUMN_NAME         VARCHAR(64 BYTE)    NOT NULL,
    PRIMARY             BOOLEAN             NOT NULL,
    CHANGED             BOOLEAN             NOT NULL,
    DATATYPE            BINARY_INTEGER      NOT NULL,
    BYTES               BINARY_INTEGER      NOT NULL,
    PRECISION           BINARY_INTEGER,
    SCALE               BINARY_INTEGER,
    NULLABLE            BINARY_INTEGER      NOT NULL,
    FLAGS               BINARY_INTEGER      NOT NULL,
    DEFAULT_TEXT        VARCHAR(1024 BYTE),
    OPTIONS             RAW(128),
    CONSTRAINT "PK_SYS_COLUMNMETA_HIS" PRIMARY KEY("OBJECT_SCN", "OBJECT_VERSION", "COLUMN_ID")
) SYSTEM 1046 TABLESPACE SYSAUX
/

CREATE INDEX IX_DIC_HIS ON SYS_COLUMNMETA_HIS (USER_ID, TABLE_ID)
TABLESPACE SYSAUX
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_COLUMNMETA_HIS
/
