CREATE TABLE SYS_TEST_UPGRADE
(
    TEST_ID          BINARY_INTEGER           NOT NULL
) SYSTEM 1045 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IDX_SYS_TEST_UPGRADE_001 ON SYS_TEST_UPGRADE(TEST_ID) TABLESPACE SYSTEM

/
