SELECT MAX(SEQUENCE#) FROM SYS.DV_ARCHIVED_LOGS;
SELECT * FROM LREP.LOGICREP_PROGRESS WHERE ID='LOGICREP0';
SELECT LREP_MODE FROM SYS.DV_DATABASE;
SHOW PARAMETERS MAX_ARCH_FILES_SIZE;
SHOW PARAMETERS ARCH_FILE_SIZE;
SHOW PARAMETERS ARCH_CLEAN_UPPER_LIMIT;