DROP TABLE IF EXISTS  T_AUTO_INCREMENT;
DROP PROCEDURE IF EXISTS Insert100Times;

CREATE TABLE T_AUTO_INCREMENT(id bigint PRIMARY KEY AUTO_INCREMENT);
CREATE OR REPLACE PROCEDURE Insert100Times IS
    counter NUMBER := 0;
BEGIN
FOR counter IN 1..100 LOOP
        INSERT INTO T_AUTO_INCREMENT VALUES (0);
END LOOP;
COMMIT;
END;
/

INSERT INTO T_AUTO_INCREMENT VALUES(0);
INSERT INTO T_AUTO_INCREMENT VALUES(0);
SELECT * FROM T_AUTO_INCREMENT;
-- [1, 100]
ALTER TABLE T_AUTO_INCREMENT AUTO_INCREMENT = 50;
INSERT INTO T_AUTO_INCREMENT VALUES(0);
SELECT * FROM T_AUTO_INCREMENT;
-- [100, 200]
ALTER TABLE T_AUTO_INCREMENT AUTO_INCREMENT = 102;
INSERT INTO T_AUTO_INCREMENT VALUES(0);
SELECT * FROM T_AUTO_INCREMENT;
call Insert100Times();
SELECT * FROM T_AUTO_INCREMENT;
update T_AUTO_INCREMENT set id = '9223372036854775806' where id = 1;
INSERT INTO T_AUTO_INCREMENT VALUES(0);
SELECT * FROM T_AUTO_INCREMENT;
INSERT INTO T_AUTO_INCREMENT VALUES(0);

DROP TABLE T_AUTO_INCREMENT;
DROP PROCEDURE Insert100Times;
