DROP TABLE IF EXISTS MICA;
CREATE TABLE MICA AS
SELECT (A.N - 1) * 100 + B.N AS K
  FROM (SELECT LEVEL N FROM SYS_DUMMY CONNECT BY LEVEL <= 100) A,
       (SELECT LEVEL N FROM SYS_DUMMY CONNECT BY LEVEL <= 100) B;

-- Expected result: 1; execution time should be less than 1 second in the gate environment.
SELECT COUNT(*) FROM MICA
 WHERE K IN (SELECT COUNT(DISTINCT K) FROM MICA);

DROP TABLE IF EXISTS MICA;
