--02
CREATE TABLE SYS_SEQUENCES
(
  UID           BINARY_INTEGER        NOT  NULL,
  ID            BINARY_INTEGER        NOT  NULL,
  NAME          VARCHAR(64)           NOT  NULL,
  MINVAL        BINARY_BIGINT,
  MAXVAL        BINARY_BIGINT,
  STEP          BINARY_BIGINT,
  CACHESIZE     BINARY_BIGINT,
  CYCLE_FLAG    BINARY_INTEGER,
  ORDER_FLAG    BINARY_INTEGER,
  ORG_SCN       BINARY_BIGINT,
  CHG_SCN       BINARY_BIGINT,
  LAST_NUMBER   BINARY_BIGINT,
  DIST_DATA     VARCHAR(1024)
)SYSTEM 4 TABLESPACE SYSTEM
/

CREATE INDEX IX_SEQ$001 ON SYS_SEQUENCES(UID, NAME) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_SEQUENCES
/

--01
CREATE TABLE SYS_LOBS
(
  USER#         BINARY_INTEGER       NOT   NULL,
  TABLE#        BINARY_INTEGER       NOT   NULL,
  COLUMN#       BINARY_INTEGER       NOT   NULL,
  SPACE#        BINARY_INTEGER       NOT   NULL,
  ENTRY         BINARY_BIGINT,
  ORG_SCN       BINARY_BIGINT,
  CHG_SCN       BINARY_BIGINT,
  CHUNK         BINARY_INTEGER,
  PCTVERSION    BINARY_INTEGER,
  RETENSION     BINARY_INTEGER,
  FLAGS         BINARY_INTEGER
)SYSTEM 5 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_LOB$001 ON SYS_LOBS(USER#, TABLE#, COLUMN#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_LOBS
/

--01
CREATE TABLE SYS_RECYCLEBIN
(
  ID                BINARY_BIGINT        NOT   NULL,
  NAME              VARCHAR(30)          NOT   NULL,
  USER#             BINARY_INTEGER       NOT   NULL,
  ORG_NAME          VARCHAR(64)          NOT   NULL,
  PARTITION_NAME    VARCHAR(64),
  TYPE#             BINARY_INTEGER       NOT   NULL,
  OPERATION#        BINARY_INTEGER       NOT   NULL,
  SPACE#            BINARY_INTEGER       NOT   NULL,
  ENTRY             BINARY_BIGINT,
  FLAGS             BINARY_INTEGER       NOT   NULL,
  ORG_SCN           BINARY_BIGINT        NOT   NULL,
  REC_SCN           BINARY_BIGINT        NOT   NULL,
  TCHG_SCN          BINARY_BIGINT,
  BASE_ID           BINARY_BIGINT        NOT   NULL,
  PURGE_ID          BINARY_BIGINT        NOT   NULL
) SYSTEM 6 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_RB$001 ON SYS_RECYCLEBIN(ID) TABLESPACE SYSTEM
/
CREATE INDEX IX_RB$002 ON SYS_RECYCLEBIN(BASE_ID, PURGE_ID) TABLESPACE SYSTEM
/
CREATE INDEX IX_RB$003 ON SYS_RECYCLEBIN(SPACE#) TABLESPACE SYSTEM
/
CREATE INDEX IX_RB$004 ON SYS_RECYCLEBIN(USER#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_RECYCLEBIN
/

--01
CREATE TABLE SYS_CONSTRAINT_DEFS
(
  USER#        BINARY_INTEGER        NOT  NULL,
  TABLE#       BINARY_INTEGER        NOT  NULL,
  CONS_NAME    VARCHAR(64)           NOT  NULL,
  CONS_TYPE    BINARY_INTEGER        NOT  NULL,
  COLS         BINARY_INTEGER,
  COL_LIST     VARCHAR(128),
  IND#		   BINARY_INTEGER,
  REF_USER#    BINARY_INTEGER,
  REF_TABLE#   BINARY_INTEGER,
  REF_CONS     BINARY_INTEGER,
  COND_TEXT    VARCHAR(2048),
  COND_DATA    BINARY(4096),
  FLAGS        BINARY_INTEGER,
  REFACT	   BINARY_INTEGER
) SYSTEM 7 TABLESPACE SYSTEM
/

CREATE INDEX IX_CONSDEF$001 ON SYS_CONSTRAINT_DEFS(USER#, TABLE#) TABLESPACE SYSTEM
/
CREATE INDEX IX_CONSDEF$002 ON SYS_CONSTRAINT_DEFS(REF_USER#, REF_TABLE#) TABLESPACE SYSTEM
/
CREATE UNIQUE INDEX IX_CONSDEF$003 ON SYS_CONSTRAINT_DEFS(USER#, CONS_NAME, TABLE#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_CONSTRAINT_DEFS
/

--01
CREATE TABLE SYS_VIEWS
(
  USER#         BINARY_INTEGER         NOT  NULL,
  ID            BINARY_INTEGER         NOT  NULL,
  NAME          VARCHAR(64)            NOT  NULL,
  COLS          BINARY_INTEGER         NOT  NULL,
  FLAGS         BINARY_INTEGER         NOT  NULL,
  ORG_SCN       BINARY_BIGINT,
  CHG_SCN       BINARY_BIGINT,
  TEXT_LENGTH   BINARY_INTEGER         NOT  NULL,
  TEXT          CLOB                   NOT  NULL,
  SQL_TYPE      BINARY_INTEGER         NOT  NULL,
  OBJ#          BINARY_INTEGER         NOT  NULL
) SYSTEM 8 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_VIEW$001 ON SYS_VIEWS(USER#, NAME) TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_VIEW$002 ON SYS_VIEWS(USER#, ID) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_VIEWS
/

--01
CREATE TABLE SYS_VIEW_COLS
(
  USER#          BINARY_INTEGER         NOT NULL,
  VIEW#          BINARY_INTEGER         NOT NULL,
  ID             BINARY_INTEGER         NOT NULL,
  NAME           VARCHAR2(128)          NOT NULL,
  DATATYPE       BINARY_INTEGER         NOT NULL,
  BYTES          BINARY_INTEGER         NOT NULL,
  PRECISION      BINARY_INTEGER,
  SCALE          BINARY_INTEGER,
  NULLABLE       BINARY_INTEGER,
  FLAGS          BINARY_INTEGER
)SYSTEM 9  TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_VIEWCOL$001 ON SYS_VIEW_COLS(USER#, VIEW#, ID) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR  SYS_VIEW_COLS
/

--01
CREATE TABLE SYS_DUMMY
(
  DUMMY          VARCHAR(1)     NOT NULL
) SYSTEM 10 TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_DUMMY
/

--03
CREATE TABLE SYS_PROCS
(
  USER#           BINARY_INTEGER       NOT NULL,
  OBJ#            BINARY_BIGINT        NOT NULL,
  NAME            VARCHAR(128)         NOT NULL,
  CLASS           BINARY_INTEGER       NOT NULL,
  TYPE            CHAR                 NOT NULL,
  SOURCE          CLOB                 NOT NULL,
  AGGREGATE       BINARY_INTEGER       NOT NULL,
  PIPELINED       BINARY_INTEGER       NOT NULL,
  TRIG_TABLE_USER VARCHAR(128),
  TRIG_TABLE      VARCHAR(128),
  ORG_SCN         BINARY_BIGINT        NOT NULL,
  CHG_SCN         BINARY_BIGINT        NOT NULL,
  TRIG_STATUS     VARCHAR(16),
  STATUS          BINARY_INTEGER       NOT NULL,
  FLAGS           BINARY_INTEGER       NULL,
  LIB_NAME        VARCHAR(64)          NULL,
  LIB_USER        VARCHAR(64)          NULL
) SYSTEM 11 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_PROC_001 ON SYS_PROCS(NAME, USER#, CLASS) TABLESPACE SYSTEM
/

CREATE INDEX IX_PROC_002 ON SYS_PROCS(TRIG_TABLE, TRIG_TABLE_USER) TABLESPACE SYSTEM
/

CREATE INDEX IX_PROC_003 ON SYS_PROCS(USER#, OBJ#) TABLESPACE SYSTEM
/

CREATE INDEX IX_PROC_004 ON SYS_PROCS(USER#, LIB_NAME) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR  SYS_PROCS
/

--01
CREATE SEQUENCE SEQ_PROC_001 START WITH 30000 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE
/

--02
CREATE TABLE SYS_EXTERNAL_TABLES
(
  TABLE#        BINARY_INTEGER    NOT NULL,
  TYPE          BINARY_INTEGER    NOT NULL,
  DIRECTORY     VARCHAR(256)      NOT NULL,
  LOCATION      VARCHAR(30)       NOT NULL,
  RECORDS_DEL   VARCHAR(1)        NOT NULL,
  FIELDS_DEL    VARCHAR(1)        NOT NULL,
  USER#         BINARY_INTEGER
) SYSTEM 12 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_EXTERNALTABLES_001 ON SYS_EXTERNAL_TABLES(USER#, TABLE#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_EXTERNAL_TABLES
/

--04
CREATE TABLE SYS_PENDING_TRANS
(
  GLOBAL_TRAN_ID  VARCHAR(256)    NOT NULL,
  LOCAL_TRAN_ID   BINARY_BIGINT,
  TLOCK_LOBS      BINARY(4000),
  TLOCK_LOBS_EXT  BLOB,
  FORMAT_ID       BINARY_BIGINT,
  BRANCH_ID       VARCHAR(128),
  OWNER           BINARY_INTEGER,
  PREPARE_SCN     BINARY_BIGINT,
  COMMIT_SCN      BINARY_BIGINT
) SYSTEM 13 TABLESPACE SYSTEM PCTFREE 20 STORAGE (INITIAL 128K)
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_PENDING_TRANS
/

--01
CREATE TABLE SYS_SYNONYMS
(
  USER#            BINARY_INTEGER     NOT  NULL,
  ID               BINARY_INTEGER     NOT  NULL,
  ORG_SCN          BINARY_BIGINT,
  CHG_SCN          BINARY_BIGINT,
  SYNONYM_NAME     VARCHAR2(64)       NOT  NULL,
  TABLE_OWNER      VARCHAR2(64),
  TABLE_NAME       VARCHAR2(64)       NOT  NULL,
  FLAGS            BINARY_INTEGER     NOT  NULL,
  TYPE             BINARY_INTEGER DEFAULT 0 NOT NULL
) SYSTEM 14 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_SYNONYM$001 ON SYS_SYNONYMS(USER#, SYNONYM_NAME) TABLESPACE SYSTEM
/

CREATE INDEX IX_SYNONYM$002 ON SYS_SYNONYMS(USER#, ID) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_SYNONYMS
/

--01
CREATE TABLE SYS_COMMENTS
(
  USER#         BINARY_INTEGER       NOT  NULL,
  TABLE#        BINARY_INTEGER       NOT  NULL,
  COLUMN#       BINARY_INTEGER,
  TEXT          VARCHAR2(4000)
) SYSTEM 15 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_COMMENT$001 ON SYS_COMMENTS(USER#, TABLE#, COLUMN#) TABLESPACE SYSTEM
/


ALTER SYSTEM LOAD DICTIONARY FOR SYS_COMMENTS
/

--01
CREATE TABLE SYS_PRIVS
(
  GRANTEE_ID    BINARY_INTEGER NOT NULL,
  GRANTEE_TYPE  BINARY_INTEGER NOT NULL,
  PRIVILEGE     BINARY_INTEGER NOT NULL,
  ADMIN_OPTION  BINARY_INTEGER NOT NULL
) SYSTEM 16 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_SYS_PRIVS$_001 ON SYS_PRIVS(GRANTEE_ID, GRANTEE_TYPE, PRIVILEGE)
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_PRIVS
/

--02
CREATE TABLE SYS_OBJECT_PRIVS
(
  GRANTEE       BINARY_INTEGER NOT NULL,
  GRANTEE_TYPE  BINARY_INTEGER NOT NULL,
  OBJECT_OWNER  BINARY_INTEGER NOT NULL,
  OBJECT_NAME   VARCHAR(64)    NOT NULL,
  OBJECT_TYPE   BINARY_INTEGER NOT NULL,
  PRIVILEGE     BINARY_INTEGER NOT NULL,
  GRANTABLE     BINARY_INTEGER NOT NULL,
  GRANTOR       BINARY_INTEGER NOT NULL
) SYSTEM 17 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_OBJECT_PRIVS$_001 ON SYS_OBJECT_PRIVS(GRANTEE, GRANTEE_TYPE, OBJECT_OWNER, OBJECT_NAME, OBJECT_TYPE, PRIVILEGE)
/

CREATE INDEX IX_OBJECT_PRIVS$_002 ON SYS_OBJECT_PRIVS(OBJECT_OWNER, OBJECT_NAME, OBJECT_TYPE)
/

CREATE INDEX IX_OBJECT_PRIVS$_004 ON SYS_OBJECT_PRIVS(GRANTOR, OBJECT_OWNER, OBJECT_NAME, OBJECT_TYPE, PRIVILEGE)
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_OBJECT_PRIVS
/

--01
CREATE TABLE SYS_USER_ROLES
(
  GRANTEE_ID        BINARY_INTEGER NOT NULL,
  GRANTEE_TYPE      BINARY_INTEGER NOT NULL,
  GRANTED_ROLE_ID   BINARY_INTEGER NOT NULL,
  ADMIN_OPTION      BINARY_INTEGER NOT NULL,
  DEFAULT_ROLE      BINARY_INTEGER
) SYSTEM 18 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_USER_ROLES$_001 ON SYS_USER_ROLES(GRANTEE_ID, GRANTEE_TYPE, GRANTED_ROLE_ID)
/

CREATE INDEX IX_USER_ROLES$_002 ON SYS_USER_ROLES(GRANTED_ROLE_ID)
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_USER_ROLES
/

--01
CREATE TABLE SYS_ROLES
(
  ID          BINARY_INTEGER NOT NULL,
  OWNER_UID   BINARY_INTEGER NOT NULL,
  NAME        VARCHAR(64)    NOT NULL,
  PASSWORD    VARCHAR(256)
) SYSTEM 19 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_ROLES$_001 ON SYS_ROLES(ID, NAME)
/

CREATE INDEX IX_ROLES$_002 ON SYS_ROLES(OWNER_UID)
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_ROLES
/

--02
CREATE TABLE SYS_HISTGRAM
(
  USER#         BINARY_INTEGER,
  TABLE#        BINARY_INTEGER,
  COL#          BINARY_INTEGER,
  BUCKET        VARCHAR(4000),
  ENDPOINT      BINARY_INTEGER,
  PART#         BINARY_INTEGER,
  EPVALUE       VARCHAR(1000),
  SPARE1        BINARY_BIGINT,
  SPARE2        BINARY_BIGINT,
  SPARE3        BINARY_BIGINT
) SYSTEM 20 TABLESPACE SYSAUX
/

CREATE INDEX IX_HIST_003 ON SYS_HISTGRAM(USER#,TABLE#,COL#,PART#,ENDPOINT)
/

ALTER SYSTEM LOAD DICTIONARY FOR  SYS_HISTGRAM
/

--03
CREATE TABLE SYS_HISTGRAM_ABSTR
(
  USER#         BINARY_INTEGER,
  TAB#          BINARY_INTEGER,
  COL#          BINARY_INTEGER,
  BUCKET_NUM    BINARY_INTEGER,
  ROW_NUM       BINARY_INTEGER,
  NULL_NUM      BINARY_INTEGER,
  ANALYZE_TIME  DATE,
  MINVALUE      VARCHAR(4000),
  MAXVALUE      VARCHAR(4000),
  DIST_NUM      BINARY_INTEGER,
  DENSITY       BINARY_DOUBLE,
  SPARE1        BINARY_BIGINT,
  SPARE2        BINARY_BIGINT,
  SPARE3        BINARY_BIGINT,
  SPARE4        BINARY_BIGINT
) SYSTEM 21 TABLESPACE SYSAUX
/

CREATE INDEX IX_HIST_HEAD_002 ON SYS_HISTGRAM_ABSTR(ANALYZE_TIME)
/

CREATE UNIQUE INDEX IX_HIST_HEAD_003 ON SYS_HISTGRAM_ABSTR(USER#,TAB#,COL#,SPARE1,SPARE2)
/

ALTER SYSTEM LOAD DICTIONARY FOR  SYS_HISTGRAM_ABSTR
/
--04
CREATE TABLE SYS_PART_OBJECTS
(
  USER#             BINARY_INTEGER       NOT   NULL,
  TABLE#            BINARY_INTEGER       NOT   NULL,
  INDEX#            BINARY_INTEGER       NOT   NULL,
  PARTTYPE          BINARY_INTEGER       NOT   NULL,
  PARTCNT#          BINARY_INTEGER       NOT   NULL,
  PARTKEYS#         BINARY_INTEGER       NOT   NULL,
  FLAGS             BINARY_INTEGER       NOT   NULL,
  INTERVAL          VARCHAR(1000),
  BINTERVAL         BINARY(200),
  SUBPARTKEYS#      BINARY_INTEGER,
  SUBPARTTYPE       BINARY_INTEGER,
  IS_SLICE          BINARY_INTEGER
) SYSTEM 22 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_PARTOBJECT$001 ON SYS_PART_OBJECTS(USER#, TABLE#, INDEX#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_PART_OBJECTS
/

--01
CREATE TABLE SYS_PART_COLUMNS
(
  USER#         BINARY_INTEGER       NOT   NULL,
  TABLE#        BINARY_INTEGER       NOT   NULL,
  COLUMN#       BINARY_INTEGER       NOT   NULL,
  POSITION#     BINARY_INTEGER       NOT   NULL,
  DATATYPE      BINARY_INTEGER       NOT   NULL
) SYSTEM 23 TABLESPACE SYSTEM
/

CREATE INDEX IX_PARTCOLUMN$001 ON SYS_PART_COLUMNS(USER#, TABLE#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_PART_COLUMNS
/

--03
CREATE TABLE SYS_TABLE_PARTS
(
  USER#         BINARY_INTEGER       NOT   NULL,
  TABLE#        BINARY_INTEGER       NOT   NULL,
  PART#         BINARY_INTEGER       NOT   NULL,
  NAME          VARCHAR(64)          NOT   NULL,
  HIBOUNDLEN    BINARY_INTEGER       NOT   NULL,
  HIBOUNDVAL    VARCHAR(4000),
  SPACE#        BINARY_INTEGER       NOT   NULL,
  ORG_SCN       BINARY_BIGINT        NOT   NULL,
  ENTRY         BINARY_BIGINT        NOT   NULL,
  INITRANS      BINARY_INTEGER       NOT   NULL,
  PCTFREE       BINARY_INTEGER       NOT   NULL,
  FLAGS         BINARY_INTEGER       NOT   NULL,
  BHIBOUNDVAL   BINARY(4000),
  ROWCNT        BINARY_INTEGER,
  BLKCNT        BINARY_INTEGER,
  EMPCNT        BINARY_INTEGER,
  AVGRLN        BINARY_INTEGER,
  SAMPLESIZE    BINARY_INTEGER,
  ANALYZETIME   DATE,
  SUBPARTCNT    BINARY_INTEGER
) SYSTEM 24 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_TABLEPART$001 ON SYS_TABLE_PARTS(USER#, TABLE#, PART#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_TABLE_PARTS
/

--03
CREATE TABLE SYS_INDEX_PARTS
(
  USER#         BINARY_INTEGER       NOT   NULL,
  TABLE#        BINARY_INTEGER       NOT   NULL,
  INDEX#        BINARY_INTEGER       NOT   NULL,
  PART#         BINARY_INTEGER       NOT   NULL,
  NAME          VARCHAR(64)          NOT   NULL,
  HIBOUNDLEN    BINARY_INTEGER       NOT   NULL,
  HIBOUNDVAL    VARCHAR(4000),
  SPACE#        BINARY_INTEGER       NOT   NULL,
  ORG_SCN       BINARY_BIGINT        NOT   NULL,
  ENTRY         BINARY_BIGINT        NOT   NULL,
  INITRANS      BINARY_INTEGER       NOT   NULL,
  PCTFREE       BINARY_INTEGER       NOT   NULL,
  FLAGS         BINARY_INTEGER       NOT   NULL,
  BHIBOUNDVAL   BINARY(4000),
  BLEVEL        BINARY_INTEGER,
  LEVEL_BLOCKS  BINARY_INTEGER,
  DISTKEY       BINARY_INTEGER,
  LBLKKEY       BINARY_DOUBLE,
  DBLKKEY       BINARY_DOUBLE,
  ANALYZETIME   DATE,
  EMPTY_LEAF_BLOCKS BINARY_INTEGER,
  CLUFAC        BINARY_INTEGER,
  SAMPLESIZE    BINARY_INTEGER,
  COMB_COLS_2_NDV BINARY_INTEGER,
  COMB_COLS_3_NDV BINARY_INTEGER,
  COMB_COLS_4_NDV BINARY_INTEGER,
  SUBPARTCNT    BINARY_INTEGER
) SYSTEM 25 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_INDEXPART$001 ON SYS_INDEX_PARTS(USER#, TABLE#, INDEX#, PART#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_INDEX_PARTS
/

--01
CREATE TABLE SYS_LOB_PARTS
(
  USER#         BINARY_INTEGER       NOT   NULL,
  TABLE#        BINARY_INTEGER       NOT   NULL,
  COLUMN#       BINARY_INTEGER       NOT   NULL,
  PART#         BINARY_INTEGER       NOT   NULL,
  SPACE#        BINARY_INTEGER       NOT   NULL,
  ORG_SCN       BINARY_BIGINT        NOT   NULL,
  ENTRY         BINARY_BIGINT        NOT   NULL,
  FLAGS         BINARY_INTEGER       NOT   NULL
) SYSTEM 26 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_LOBPART$001 ON SYS_LOB_PARTS(USER#, TABLE#, COLUMN#, PART#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_LOB_PARTS
/

--01
CREATE TABLE SYS_SHADOW_INDEXES
(
  USER#         BINARY_INTEGER          NOT NULL,
  TABLE#        BINARY_INTEGER          NOT NULL,
  ID            BINARY_INTEGER          NOT NULL,
  NAME          VARCHAR(64)             NOT NULL,
  SPACE#        BINARY_INTEGER          NOT NULL,
  SEQUENCE#     BINARY_BIGINT           NOT NULL,
  ENTRY         BINARY_BIGINT           NOT NULL,
  IS_PRIMARY    BINARY_INTEGER          NOT NULL,
  IS_UNIQUE     BINARY_INTEGER          NOT NULL,
  TYPE          BINARY_INTEGER          NOT NULL,
  COLS          BINARY_INTEGER          NOT NULL,
  COL_LIST      VARCHAR(128)            NOT NULL,
  INITRANS      BINARY_INTEGER          NOT NULL,
  CR_MODE       BINARY_INTEGER          NOT NULL,
  FLAGS         BINARY_INTEGER          NOT NULL,
  PARTED        BINARY_INTEGER          NOT NULL,
  PCTFREE       BINARY_INTEGER          NOT NULL
) SYSTEM 27 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_SHADOW_INDEX$_001 ON SYS_SHADOW_INDEXES(USER#, TABLE#);
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_SHADOW_INDEXES
/

--01
CREATE TABLE SYS_PROFILE
(
  NAME           VARCHAR(64)          NOT NULL,
  PROFILE#       BINARY_INTEGER       NOT NULL,
  RESOURCE#      BINARY_INTEGER       NOT NULL,
  THRESHOLD      BINARY_BIGINT        NOT NULL
) SYSTEM 28 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_PROFILE$_001 ON SYS_PROFILE(PROFILE#, RESOURCE#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_PROFILE
/

--05
CREATE TABLE SYS_SHADOW_INDEX_PARTS
(
  USER#         BINARY_INTEGER       NOT   NULL,
  TABLE#        BINARY_INTEGER       NOT   NULL,
  INDEX#        BINARY_INTEGER       NOT   NULL,
  PART#         BINARY_INTEGER       NOT   NULL,
  NAME          VARCHAR(64)          NOT   NULL,
  HIBOUNDLEN    BINARY_INTEGER       NOT   NULL,
  HIBOUNDVAL    VARCHAR(4000),
  SPACE#        BINARY_INTEGER       NOT   NULL,
  ORG_SCN       BINARY_BIGINT        NOT   NULL,
  ENTRY         BINARY_BIGINT        NOT   NULL,
  INITRANS      BINARY_INTEGER       NOT   NULL,
  PCTFREE       BINARY_INTEGER       NOT   NULL,
  FLAGS         BINARY_INTEGER,
  BHIBOUNDVAL   BINARY(4000),
  PARENT_PART#  BINARY_INTEGER
) SYSTEM 29 TABLESPACE SYSTEM
/

CREATE INDEX IX_SHW_INDEXPART$001 ON SYS_SHADOW_INDEX_PARTS(USER#, TABLE#, INDEX#, PART#, PARENT_PART#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_SHADOW_INDEX_PARTS
/

--02
CREATE TABLE SYS_BACKUP_SETS
(
  RECID                   BINARY_BIGINT     NOT NULL,
  TYPE                    BINARY_INTEGER    NOT NULL,
  STAGE                   BINARY_INTEGER    NOT NULL,
  STATUS                  BINARY_INTEGER    NOT NULL,
  INCREMENTAL_LEVEL       BINARY_INTEGER    NOT NULL,
  TAG                     VARCHAR(64)       NOT NULL,
  SCN                     BINARY_BIGINT     NOT NULL,
  LSN                     BINARY_BIGINT     NOT NULL,
  DEVICE_TYPE             BINARY_INTEGER    NOT NULL,
  BASE_TAG                VARCHAR(64)       NOT NULL,
  DIR                     VARCHAR(256)      NOT NULL,
  RESETLOGS               BINARY_INTEGER    NOT NULL,
  POLICY                  VARCHAR(128)      NOT NULL,
  RCY_ASN                 BINARY_INTEGER    NOT NULL,
  RCY_OFFSET              BINARY_BIGINT     NOT NULL,
  RCY_LFN                 BINARY_BIGINT     NOT NULL,
  LRP_ASN                 BINARY_INTEGER    NOT NULL,
  LRP_OFFSET              BINARY_BIGINT     NOT NULL,
  LRP_LFN                 BINARY_BIGINT     NOT NULL,
  START_TIME              TIMESTAMP         NOT NULL,
  COMPLETION_TIME         TIMESTAMP         NOT NULL,
  MAX_BUFFER_SIZE         BINARY_INTEGER    DEFAULT 8388608   NOT NULL,
  DB_VERSION              VARCHAR(256)      DEFAULT 'ec669c7' NOT NULL,
  LRP_LSN                 BINARY_BIGINT      NOT NULL
) SYSTEM 30 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_BACKUP_SET$001 ON SYS_BACKUP_SETS(RECID) TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_BACKUP_SET$002 ON SYS_BACKUP_SETS(TAG) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_BACKUP_SETS
/

--01
CREATE SEQUENCE OBJECT_ID$
MINVALUE 1000
NOCACHE
/

--02
CREATE TABLE SYS_DATA_NODES
(
  NODE_ID          BINARY_INTEGER    NOT NULL,
  NODE_NAME        VARCHAR(128)      NOT NULL,
  NODE_TYPE        VARCHAR(128)      NOT NULL,
  NODE_HOST        VARCHAR(64)       NOT NULL,
  NODE_PORT        BINARY_INTEGER    NOT NULL,
  GROUP_ID         BINARY_INTEGER    NOT NULL,
  IS_PRIMARY       BINARY_INTEGER    ,
  WEIGHT           BINARY_INTEGER    ,
  NODE_USER        VARCHAR(128)      NOT NULL,
  NODE_PASSWORD    VARCHAR(512)      NOT NULL,
  MIN_CONN         BINARY_INTEGER    NOT NULL,
  MAX_CONN         BINARY_INTEGER    NOT NULL
) SYSTEM 31 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_DATA_NODES_ID$001 ON SYS_DATA_NODES(NODE_ID) TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_DATA_NODES_NAME$002 ON SYS_DATA_NODES(NODE_NAME) TABLESPACE SYSTEM
/

CREATE INDEX IX_DATA_NODES_HOST_PORT$003 ON SYS_DATA_NODES(NODE_HOST, NODE_PORT) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_DATA_NODES
/

--03
CREATE TABLE SYS_PENDING_DIST_TRANS
(
  GLOBAL_TRAN_ID   VARCHAR(256)       NOT NULL,
  TRAN_COMMIT_TIME TIMESTAMP          NOT NULL,
  TRX_STATUS       BINARY_INTEGER     NOT NULL,
  NEED_CLEAN       BINARY_INTEGER     NOT NULL
) SYSTEM 32 TABLESPACE SYSTEM PCTFREE 80 STORAGE (INITIAL 128K)
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_PENDING_DIST_TRANS
/

--04
CREATE TABLE SYS_DISTRIBUTE_STRATEGIES
(
  USER#            BINARY_INTEGER     NOT NULL,
  TABLE#           BINARY_INTEGER     NOT NULL,
  DIST_DATA        VARCHAR(1024)      NOT NULL,
  BUCKETS          BLOB,
  SLICE_COUNT      BINARY_INTEGER,
  FROZEN_STATUS    BINARY_INTEGER,
  DIST_TEXT        VARCHAR(1024)
) SYSTEM 33 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_DISTRIBUTE_STRATEGY$001 ON SYS_DISTRIBUTE_STRATEGIES(USER#, TABLE#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_DISTRIBUTE_STRATEGIES
/

--01
CREATE TABLE SYS_GARBAGE_SEGMENTS
(
  UID            BINARY_INTEGER,
  OID            BINARY_INTEGER,
  INDEX_ID       BINARY_INTEGER,
  COLUMN_ID      BINARY_INTEGER,
  SPACE          BINARY_INTEGER,
  ENTRY          BINARY_BIGINT,
  ORG_SCN        BINARY_BIGINT,
  SEG_SCN        BINARY_BIGINT,
  INITRANS       BINARY_INTEGER,
  PCTFREE        BINARY_INTEGER,
  OP_TYPE        BINARY_INTEGER,
  REUSE          BINARY_INTEGER,
  SERIAL         BINARY_BIGINT,
  SPARE2         BINARY_INTEGER,
  SPARE3         BINARY_INTEGER
) SYSTEM 34 TABLESPACE SYSTEM
/

CREATE INDEX IX_GARBAGE_SEGMENT$001 ON SYS_GARBAGE_SEGMENTS(UID, OID) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_GARBAGE_SEGMENTS
/

--01
CREATE TABLE SYS_PART_STORES
(
  USER#             BINARY_INTEGER       NOT   NULL,
  TABLE#            BINARY_INTEGER       NOT   NULL,
  INDEX#            BINARY_INTEGER       NOT   NULL,
  POSITION#         BINARY_INTEGER       NOT   NULL,
  SPACE#            BINARY_INTEGER       NOT   NULL
) SYSTEM 35 TABLESPACE SYSTEM
/

CREATE INDEX IX_PARTSTORE$001 ON SYS_PART_STORES(USER#, TABLE#, INDEX#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_PART_STORES
/

--01
CREATE TABLE SYS_USER_HISTORY
(
  USER#                   BINARY_INTEGER        NOT NULL,
  PASSWORD                BINARY(512),
  PASSWORD_DATE           DATE
) SYSTEM 36 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_USER_HISTORY$001 ON SYS_USER_HISTORY(USER#, PASSWORD_DATE) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_USER_HISTORY
/

--01
CREATE TABLE SYS_PROC_ARGS
(
  USER#           BINARY_INTEGER      NOT NULL,
  OBJECT_NAME     VARCHAR(128)        NOT NULL,
  ARGUMENT_NAME   VARCHAR(128),
  POSITION        BINARY_INTEGER      NOT NULL,
  SEQUENCE        BINARY_INTEGER      NOT NULL,
  DATA_LEVEL      BINARY_INTEGER      NOT NULL,
  DATA_TYPE       BINARY_INTEGER      NOT NULL,
  DEFAULTED       BINARY_INTEGER      NOT NULL,
  DEFAULT_VALUE   VARCHAR(128),
  DEFAULT_LENGTH  VARCHAR(128),
  IN_OUT          BINARY_INTEGER       NOT NULL,
  DATA_LENGTH     BINARY_INTEGER,
  DATA_PRECISION  BINARY_INTEGER,
  DATA_SCALE      BINARY_INTEGER,
  TYPE#           BINARY_BIGINT,
  RESERVERD       VARCHAR(128),
  PACKAGE         VARCHAR(128),
  PROC_SEQ        BINARY_INTEGER   DEFAULT 1  NOT NULL,
  OVERLOAD        BINARY_INTEGER   DEFAULT 0  NOT NULL,
  RESERVERD1      BINARY_INTEGER,
  RESERVERD2      BINARY_INTEGER,
  RESERVERD3      VARCHAR(128),
  RESERVERD4      VARCHAR(128),
  RESERVERD5      VARCHAR(128)
) SYSTEM 37 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_PROCARGU_001 ON SYS_PROC_ARGS(USER#, OBJECT_NAME, PACKAGE, SEQUENCE, OVERLOAD) TABLESPACE SYSTEM
/

CREATE INDEX IX_PROCARGU_002 ON SYS_PROC_ARGS(USER#, PACKAGE) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR  SYS_PROC_ARGS
/

--02
CREATE TABLE SYS_LOGIC_REPL
(
  USER# 	BINARY_INTEGER	NOT NULL,
  TABLE#	BINARY_INTEGER	NOT NULL,
  STATUS	BINARY_INTEGER	NOT NULL,
  INDEX#	BINARY_INTEGER,
  PARTITION_IDS CLOB
) SYSTEM 38 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_LOGICREP$_001 ON SYS_LOGIC_REPL(USER#, TABLE#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_LOGIC_REPL
/

--01
CREATE TABLE SYS_DML_STATS
(
  USER#         BINARY_INTEGER       NOT   NULL,
  TABLE#        BINARY_INTEGER       NOT   NULL,
  INSERTS       BINARY_INTEGER       NOT   NULL,
  UPDATES       BINARY_INTEGER       NOT   NULL,
  DELETES       BINARY_INTEGER       NOT   NULL,
  MODIFY_TIME   TIMESTAMP            NOT   NULL,
  FLAGS         BINARY_INTEGER       NOT   NULL,
  DROP_SEGMENTS BINARY_INTEGER       NOT   NULL,
  PARTED        BINARY_INTEGER,
  PART#         BINARY_INTEGER
) SYSTEM 39 TABLESPACE SYSTEM
/

CREATE INDEX IX_MODS_001 ON SYS_DML_STATS(USER#, TABLE#) TABLESPACE SYSTEM
/

CREATE INDEX IX_MODS_002 ON SYS_DML_STATS(MODIFY_TIME) TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_MODS_003 ON SYS_DML_STATS(USER#, TABLE#, PART#) TABLESPACE SYSTEM
/
ALTER SYSTEM LOAD DICTIONARY FOR  SYS_DML_STATS
/

--01
CREATE TABLE SYS_DEPENDENCIES
(
D_OWNER#    BINARY_INTEGER     NOT NULL,
D_OBJ#      BINARY_BIGINT      NOT NULL,
D_TYPE#     BINARY_INTEGER     NOT NULL,
D_SCN       BINARY_BIGINT      NOT NULL,
ORDER#      BINARY_INTEGER     NOT NULL,
P_OWNER#    BINARY_INTEGER     NOT NULL,
P_OBJ#      BINARY_BIGINT      NOT NULL,
P_TYPE#     BINARY_INTEGER     NOT NULL,
P_SCN       BINARY_BIGINT      NOT NULL,
D_NAME      VARCHAR(64)                ,
P_NAME      VARCHAR(64)
) SYSTEM 40 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_DEPENDENCY1 ON SYS_DEPENDENCIES (D_OWNER#,D_OBJ#, D_TYPE#, ORDER#) TABLESPACE SYSTEM
/

CREATE INDEX IX_DEPENDENCY2 ON SYS_DEPENDENCIES (P_OWNER#,P_OBJ#, P_TYPE#) TABLESPACE SYSTEM
/

CREATE INDEX IX_DEPENDENCY3 ON SYS_DEPENDENCIES (D_NAME) TABLESPACE SYSTEM
/

CREATE INDEX IX_DEPENDENCY4 ON SYS_DEPENDENCIES (P_NAME) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR  SYS_DEPENDENCIES
/

--01
CREATE TABLE SYS_LINKS
(
  OWNER#          INTEGER       NOT NULL,
  NAME            VARCHAR2(128) NOT NULL,
  CTIME           DATE          NOT NULL,
  NODE_ID         INTEGER       NOT NULL,
  HOST            VARCHAR2(2000),
  USERID          VARCHAR2(64),
  PASSWORD        VARCHAR2(512)
) SYSTEM 42 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_LINK$001 ON SYS_LINKS(OWNER#, NAME) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_LINKS
/

--02
CREATE TABLE SYS_DISTRIBUTE_RULES
(
  UID           INTEGER        NOT  NULL,
  ID            INTEGER        NOT  NULL,
  DIST_DATA     VARCHAR(1024)  NOT  NULL,
  BUCKETS       BLOB,
  NAME          VARCHAR(64)    NOT  NULL,
  ORG_SCN       BIGINT,
  CHG_SCN       BIGINT,
  COLUMNS       VARCHAR(1024),
  COLUMN_COUNT  INTEGER        NOT  NULL
)SYSTEM 41 TABLESPACE SYSTEM
/

CREATE INDEX IX_DISTRIBUTE_RULE$001 ON SYS_DISTRIBUTE_RULES(NAME) TABLESPACE SYSTEM
/

CREATE INDEX IX_DISTRIBUTE_RULE$002 ON SYS_DISTRIBUTE_RULES(ID) TABLESPACE SYSTEM
/

CREATE INDEX IX_DISTRIBUTE_RULE$003 ON SYS_DISTRIBUTE_RULES(UID) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_DISTRIBUTE_RULES
/

--01
CREATE ROLE DBA
/

--01
CREATE ROLE RESOURCE
/

GRANT CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE, CREATE TABLE TO RESOURCE
/

--01
CREATE GLOBAL TEMPORARY TABLE SYS_TMP_SEG_STATS
(
ORG_SCN             	 BINARY_BIGINT   PRIMARY KEY,
UID                      BINARY_INTEGER,
OID                      BINARY_INTEGER,
LOGIC_READS       	 BINARY_BIGINT,
PHYSICAL_WRITES          BINARY_BIGINT,
PHYSICAL_READS           BINARY_BIGINT,
ITL_WAITS                 BINARY_BIGINT,
BUF_BUSY_WAITS            BINARY_BIGINT,
ROW_LOCK_WAITS            BINARY_BIGINT
)SYSTEM 43 ON COMMIT PRESERVE ROWS
/
CREATE INDEX IDX_OBJECT ON SYS_TMP_SEG_STATS(UID, OID)
/
ALTER SYSTEM LOAD DICTIONARY FOR  SYS_TMP_SEG_STATS
/
--01
CREATE GLOBAL TEMPORARY TABLE EXP_TAB_RELATIONS
(
  TBL_NAME     VARCHAR(64),
  TBL_PARENT   VARCHAR(64)
) ON COMMIT PRESERVE ROWS
/
ALTER SYSTEM LOAD DICTIONARY FOR  EXP_TAB_RELATIONS
/

--01
CREATE GLOBAL TEMPORARY TABLE EXP_TAB_ORDERS
(
  TBL_NAME     VARCHAR(64),
  TBL_LEVEL    BINARY_INTEGER
) ON COMMIT PRESERVE ROWS
/
ALTER SYSTEM LOAD DICTIONARY FOR  EXP_TAB_ORDERS
/

--02
CREATE TABLE SYS_JOBS
(
  JOB             BINARY_BIGINT NOT NULL,
  LOWNER          VARCHAR(64) NOT NULL,
  POWNER          VARCHAR(64) NOT NULL,
  COWNER          VARCHAR(64) NOT NULL,
  LAST_DATE       DATE,
  THIS_DATE       DATE,
  NEXT_DATE       DATE NOT NULL,
  TOTAL           BINARY_INTEGER DEFAULT 0 NOT NULL,
  INTERVAL#       VARCHAR(200) NOT NULL,
  FAILURES        BINARY_INTEGER DEFAULT 0 NOT NULL,
  BROKEN          BINARY_INTEGER DEFAULT 0 NOT NULL,
  WHAT            VARCHAR(4000) NOT NULL,
  CREATE_DATE     DATE NOT NULL,
  INSTANCE        BINARY_INTEGER DEFAULT 0 NOT NULL
)SYSTEM 45 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX SYS.I_JOB_1 ON SYS.SYS_JOBS (JOB)  TABLESPACE SYSTEM
/
ALTER SYSTEM LOAD DICTIONARY FOR SYS_JOBS
/

--01
CREATE SEQUENCE SYS.JOBSEQ MINVALUE 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE
/

--01
CREATE TABLE SYS_SQL_MAPS
(
  SRC_HASHCODE BINARY_INTEGER NOT NULL,
  SRC_TEXT CLOB NOT NULL,
  DST_TEXT CLOB NOT NULL,
  USER#    BINARY_INTEGER NOT NULL
)SYSTEM 46 TABLESPACE SYSTEM
/

CREATE INDEX IDX_SQL_MAP_001 ON SYS_SQL_MAPS(SRC_HASHCODE)
/
CREATE INDEX IDX_SQL_MAP_002 ON SYS_SQL_MAPS(USER#)
/
ALTER SYSTEM LOAD DICTIONARY FOR SYS_SQL_MAPS
/

--01
CREATE TABLE SYS_SYNC_INFO
(
  SYNC_TIME       BINARY_BIGINT
)SYSTEM 47 TABLESPACE SYSTEM
/
ALTER SYSTEM LOAD DICTIONARY FOR SYS_SYNC_INFO
/
--01
CREATE TABLE SYS_DIST_DDL_LOGINFO
(
  DIST_DDL_ID      VARCHAR(256)       NOT NULL,
  GROUP_ID         BINARY_INTEGER     NOT NULL,
  DATANODE_ID      BINARY_INTEGER     NOT NULL,
  DDL              CLOB               NOT NULL,
  CREATE_TIME  		 TIMESTAMP          NOT NULL,
  EXPIRED_TIME  	 TIMESTAMP          NOT NULL,
  RETRY_TIMES      BINARY_INTEGER     NOT NULL,
  STATUS           BINARY_INTEGER     NOT NULL
) SYSTEM 48 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_DIST_DDL_LOGINFO_001 ON SYS_DIST_DDL_LOGINFO(DIST_DDL_ID) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_DIST_DDL_LOGINFO
/

--01
CREATE TABLE SYS_AUDIT
(
  CTIME            VARCHAR(68),
  SESSIONID        BINARY_INTEGER,
  STMTID           BINARY_INTEGER,
  USERNAME         VARCHAR(68),
  HOSTNAME         VARCHAR(68),
  ACTION           VARCHAR(68),
  RETURNCODE       BINARY_INTEGER,
  SQLTEXT          VARCHAR(8000)
) SYSTEM 49 TABLESPACE SYSTEM
/


ALTER SYSTEM LOAD DICTIONARY FOR SYS_AUDIT
/

--03
CREATE TABLE SYS_REBALANCE_TASK
(
  REBALANCE_ID     VARCHAR(256)       NOT NULL,
  TABLE_NAME       VARCHAR(64)        NOT NULL,
  STAGING_NAME     VARCHAR(64)        NOT NULL,
  BACKUP_NAME      VARCHAR(64),
  REBALANCE_ROWS   BINARY_BIGINT DEFAULT 0 NOT NULL,
  BACKUP_ROWS      BINARY_BIGINT DEFAULT 0 NOT NULL,
  INC_LOCAL        BINARY_BIGINT DEFAULT 0 NOT NULL,
  INC_REMOTE       BINARY_BIGINT DEFAULT 0 NOT NULL,
  BEGIN_TIME  		 TIMESTAMP          NOT NULL,
  END_TIME  		   TIMESTAMP,
  REBALANCE_STATUS BINARY_INTEGER     NOT NULL,
  USER_NAME         VARCHAR(64),
  REBA_GROUPS       VARCHAR(64),
  TASK_ID          BINARY_INTEGER DEFAULT 0 NOT NULL,
  SRC_GROUP_ID     BINARY_INTEGER,
  DEST_GROUP_ID    BINARY_INTEGER,
  PARTITIONS       CLOB
) SYSTEM 50 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_REBALANCE_TASK_001 ON SYS_REBALANCE_TASK(REBALANCE_ID, TABLE_NAME, TASK_ID) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_REBALANCE_TASK
/

--02
CREATE TABLE SYS_RSRC_PLANS
(
  ID          BINARY_INTEGER NOT NULL,
  NAME        VARCHAR(64) NOT NULL,
  NUM_RULES   BINARY_INTEGER NOT NULL,
  DESCRIPTION VARCHAR(256),
  TYPE#       BINARY_INTEGER DEFAULT 0
) SYSTEM 51 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_RSRC_PLANS_001 ON SYS_RSRC_PLANS(NAME) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_RSRC_PLANS
/

--01
CREATE TABLE SYS_RSRC_CONTROL_GROUPS
(
  ID          BINARY_INTEGER NOT NULL,
  NAME        VARCHAR(64) NOT NULL,
  DESCRIPTION VARCHAR(256)
) SYSTEM 52 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_RSRC_CGROUP_001 ON SYS_RSRC_CONTROL_GROUPS(NAME) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_RSRC_CONTROL_GROUPS
/

--01
CREATE TABLE SYS_RSRC_GROUP_MAPPINGS
(
  ATTRIBUTE     VARCHAR(64) NOT NULL,
  VALUE         VARCHAR(128) NOT NULL,
  CONTROL_GROUP VARCHAR(64) NOT NULL
) SYSTEM 53 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_RSRC_CGROUP_MAPPINGS_001 ON SYS_RSRC_GROUP_MAPPINGS(ATTRIBUTE, VALUE) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_RSRC_GROUP_MAPPINGS
/

--01
CREATE TABLE SYS_RSRC_PLAN_RULES
(
  PLAN              VARCHAR(64) NOT NULL,
  CONTROL_GROUP     VARCHAR(64) NOT NULL,
  CPU               BINARY_INTEGER,
  SESSIONS          BINARY_INTEGER,
  ACTIVE_SESS       BINARY_INTEGER,
  QUEUE_TIME        BINARY_INTEGER,
  MAX_EXEC_TIME     BINARY_INTEGER,
  TEMP_POOL         BINARY_INTEGER,
  MAX_IOPS          BINARY_INTEGER,
  MAX_COMMITS       BINARY_INTEGER,
  DESCRIPTION       VARCHAR(256)
) SYSTEM 54 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_RSRC_PLAN_RULES_001 ON SYS_RSRC_PLAN_RULES(PLAN, CONTROL_GROUP) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_RSRC_PLAN_RULES
/

--01
CREATE TABLE SYS_DIRECTORIES
(
  USER#            BINARY_INTEGER    NOT NULL,
  DIRECTORY_NAME   VARCHAR(64)       NOT NULL,
  DIRECTORY_PATH   VARCHAR(256)      NOT NULL
) SYSTEM 55 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_DIRECTORY_001 ON SYS_DIRECTORIES(DIRECTORY_NAME) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_DIRECTORIES
/

--01
CREATE TABLE SYS_SUB_TABLE_PARTS
(
  USER#         BINARY_INTEGER       NOT   NULL,
  TABLE#        BINARY_INTEGER       NOT   NULL,
  SUBPART#      BINARY_INTEGER       NOT   NULL,
  NAME          VARCHAR(64)          NOT   NULL,
  HIBOUNDLEN    BINARY_INTEGER       NOT   NULL,
  HIBOUNDVAL    VARCHAR(4000),
  SPACE#        BINARY_INTEGER       NOT   NULL,
  ORG_SCN       BINARY_BIGINT        NOT   NULL,
  ENTRY         BINARY_BIGINT        NOT   NULL,
  INITRANS      BINARY_INTEGER       NOT   NULL,
  PCTFREE       BINARY_INTEGER       NOT   NULL,
  FLAGS         BINARY_INTEGER       NOT   NULL,
  BHIBOUNDVAL   BINARY(4000),
  ROWCNT        BINARY_INTEGER,
  BLKCNT        BINARY_INTEGER,
  EMPCNT        BINARY_INTEGER,
  AVGRLN        BINARY_INTEGER,
  SAMPLESIZE    BINARY_INTEGER,
  ANALYZETIME   DATE,
  PARENT_PART#  BINARY_INTEGER       NOT   NULL
) SYSTEM 56 TABLESPACE SYSTEM
/
CREATE UNIQUE INDEX IX_SUBTABLEPART$001 ON SYS_SUB_TABLE_PARTS(USER#, TABLE#, PARENT_PART#, SUBPART#) TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_SUBTABLEPART$002 ON SYS_SUB_TABLE_PARTS(USER#, TABLE#, NAME) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_SUB_TABLE_PARTS
/

--01
CREATE TABLE SYS_SUB_PART_COLUMNS
(
  USER#         BINARY_INTEGER       NOT   NULL,
  TABLE#        BINARY_INTEGER       NOT   NULL,
  COLUMN#       BINARY_INTEGER       NOT   NULL,
  POSITION#     BINARY_INTEGER       NOT   NULL,
  DATATYPE      BINARY_INTEGER       NOT   NULL
) SYSTEM 57 TABLESPACE SYSTEM
/
CREATE INDEX IX_SUBPARTCOLUMN$001 ON SYS_SUB_PART_COLUMNS(USER#, TABLE#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_SUB_PART_COLUMNS
/

--01
CREATE TABLE SYS_SUB_LOB_PARTS
(
  USER#         BINARY_INTEGER       NOT   NULL,
  TABLE#        BINARY_INTEGER       NOT   NULL,
  COLUMN#       BINARY_INTEGER       NOT   NULL,
  SUBPART#      BINARY_INTEGER       NOT   NULL,
  SPACE#        BINARY_INTEGER       NOT   NULL,
  ORG_SCN       BINARY_BIGINT        NOT   NULL,
  ENTRY         BINARY_BIGINT        NOT   NULL,
  FLAGS         BINARY_INTEGER       NOT   NULL,
  PARENT_PART#  BINARY_INTEGER       NOT   NULL
) SYSTEM 58 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_SUBLOBPART$001 ON SYS_SUB_LOB_PARTS(USER#, TABLE#, PARENT_PART#, COLUMN#, SUBPART#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_SUB_LOB_PARTS
/

--01
CREATE TABLE SYS_SUB_INDEX_PARTS
(
  USER#         BINARY_INTEGER       NOT   NULL,
  TABLE#        BINARY_INTEGER       NOT   NULL,
  INDEX#        BINARY_INTEGER       NOT   NULL,
  SUBPART#      BINARY_INTEGER       NOT   NULL,
  NAME          VARCHAR(64)          NOT   NULL,
  HIBOUNDLEN    BINARY_INTEGER       NOT   NULL,
  HIBOUNDVAL    VARCHAR(4000),
  SPACE#        BINARY_INTEGER       NOT   NULL,
  ORG_SCN       BINARY_BIGINT        NOT   NULL,
  ENTRY         BINARY_BIGINT        NOT   NULL,
  INITRANS      BINARY_INTEGER       NOT   NULL,
  PCTFREE       BINARY_INTEGER       NOT   NULL,
  FLAGS         BINARY_INTEGER       NOT   NULL,
  BHIBOUNDVAL   BINARY(4000),
  BLEVEL        BINARY_INTEGER,
  LEVEL_BLOCKS  BINARY_INTEGER,
  DISTKEY       BINARY_INTEGER,
  LBLKKEY       BINARY_DOUBLE,
  DBLKKEY       BINARY_DOUBLE,
  ANALYZETIME   DATE,
  EMPTY_LEAF_BLOCKS BINARY_INTEGER,
  CLUFAC        BINARY_INTEGER,
  SAMPLESIZE    BINARY_INTEGER,
  COMB_COLS_2_NDV BINARY_INTEGER,
  COMB_COLS_3_NDV BINARY_INTEGER,
  COMB_COLS_4_NDV BINARY_INTEGER,
  PARENT_PART#    BINARY_INTEGER       NOT   NULL
) SYSTEM 59 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_SUBINDEXPART$001 ON SYS_SUB_INDEX_PARTS(USER#, TABLE#, INDEX#, PARENT_PART#, SUBPART#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_SUB_INDEX_PARTS
/

--01
CREATE TABLE SYS_SUB_PART_TEMPLATE
(
  USER#         BINARY_INTEGER       NOT   NULL,
  TABLE#        BINARY_INTEGER       NOT   NULL,
  NAME          VARCHAR(64)          NOT   NULL,
  POSITION      BINARY_INTEGER       NOT   NULL,
  SPACE#        BINARY_INTEGER       NOT   NULL,
  HIBOUNDLEN    BINARY_INTEGER       NOT   NULL,
  HIBOUNDVAL    VARCHAR(4000),
  INITRANS      BINARY_INTEGER       NOT   NULL,
  PCTFREE       BINARY_INTEGER       NOT   NULL,
  FLAGS         BINARY_INTEGER       NOT   NULL,
  BHIBOUNDVAL   BINARY(4000)
) SYSTEM 60 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_SUBPARTTEMPLATE$001 ON SYS_SUB_PART_TEMPLATE(USER#, TABLE#, POSITION) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_SUB_PART_TEMPLATE
/

--01
CREATE TABLE SYS_STORAGE
(
  ORG_SCN          BINARY_BIGINT        NOT   NULL,
  INITIAL_PAGES    BINARY_INTEGER       NOT   NULL,
  MAX_EXTENTS      BINARY_INTEGER       NOT   NULL
) SYSTEM 61 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_STORAGE_001 ON SYS_STORAGE(ORG_SCN) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_STORAGE
/

--01
CREATE TABLE SYS_CLUSTER_DDL
(
  SID            BINARY_INTEGER     NOT NULL,
  LSN            BINARY_BIGINT      NOT NULL,
  LOGIC_LOG      BLOB               NOT NULL
) SYSTEM 62 TABLESPACE SYSTEM
/

CREATE INDEX IX_CLUSTER_DDL$001 ON SYS_CLUSTER_DDL(SID) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_CLUSTER_DDL
/

--01
CREATE TABLE SYS_TYPES
(
  UID                BINARY_INTEGER,
  TYPE_OID           BINARY_BIGINT,
  TYPE_NAME          VARCHAR(64),
  TYPE_CODE          VARCHAR(8),
  ATTRIBUTES         BINARY_INTEGER,
  METHODS            BINARY_INTEGER,
  PREDEFINED         BINARY_INTEGER,
  INCOMPLETE         BINARY_INTEGER,
  FINAL              BINARY_INTEGER,
  INSTANTIABLE       BINARY_INTEGER,
  SUPERTYPE_UID      BINARY_INTEGER,
  SUPERTYPE_OID      BINARY_INTEGER,
  SUPERTYPE_NAME     VARCHAR(64),
  LOCAL_ATTRIBUTES   BINARY_INTEGER,
  LOCAL_METHODS      BINARY_INTEGER,
  ORG_SCN            BINARY_BIGINT,
  CHG_SCN            BINARY_BIGINT
)SYSTEM 1024 TABLESPACE SYSTEM
/
CREATE UNIQUE INDEX IDX_TYPE_001 ON SYS_TYPES(UID, TYPE_OID)
/
CREATE UNIQUE INDEX IDX_TYPE_002 ON SYS_TYPES(UID, TYPE_NAME)
/
ALTER SYSTEM LOAD DICTIONARY FOR SYS_TYPES
/

--01
CREATE TABLE SYS_TYPE_ATTRS
(
  UID                BINARY_INTEGER,
  TYPE_OID           BINARY_BIGINT,
  TYPE_NAME          VARCHAR(64),
  ATTR_NAME          VARCHAR(64),
  ATTR_NO            BINARY_INTEGER,
  ATTR_TYPE_MOD      BINARY_INTEGER,
  ATTR_TYPE_UID      BINARY_INTEGER,
  ATTR_TYPE_NAME     VARCHAR(64),
  ATTR_TYPE          BINARY_INTEGER,
  LENGTH             BINARY_INTEGER,
  PRECISION          BINARY_INTEGER,
  SCALE              BINARY_INTEGER,
  CHAR_SET           BINARY_INTEGER,
  INHERITED          BINARY_INTEGER
)SYSTEM 1025 TABLESPACE SYSTEM
/
CREATE UNIQUE INDEX IDX_TYPE_ATTR_001 ON SYS_TYPE_ATTRS(UID, TYPE_OID, ATTR_NO)
/
CREATE INDEX IDX_TYPE_ATTR_002 ON SYS_TYPE_ATTRS(UID, TYPE_NAME)
/
ALTER SYSTEM LOAD DICTIONARY FOR  SYS_TYPE_ATTRS
/

--01
CREATE TABLE SYS_TYPE_METHODS
(
  UID                BINARY_INTEGER,
  TYPE_OID           BINARY_BIGINT,
  TYPE_NAME          VARCHAR(64),
  METHOD_NAME        VARCHAR(64),
  METHOD_NO          BINARY_INTEGER,
  METHOD_TYPE        BINARY_INTEGER,
  PARAMETERS         BINARY_INTEGER,
  RESULTS            BINARY_INTEGER,
  FINAL              BINARY_INTEGER,
  INSTANTIABLE       BINARY_INTEGER,
  OVERRIDING         BINARY_INTEGER,
  INHERITED          BINARY_INTEGER
)SYSTEM 1026 TABLESPACE SYSTEM
/
CREATE UNIQUE INDEX IDX_TYPE_METHOD_001 ON SYS_TYPE_METHODS(UID, TYPE_OID, METHOD_NO)
/
CREATE INDEX IDX_TYPE_METHOD_002 ON SYS_TYPE_METHODS(UID, TYPE_NAME)
/
ALTER SYSTEM LOAD DICTIONARY FOR SYS_TYPE_METHODS
/

--01
CREATE TABLE SYS_COLL_TYPES
(
  UID                BINARY_INTEGER,
  TYPE_OID           BINARY_BIGINT,
  TYPE_NAME          VARCHAR(64),
  COLL_TYPE          VARCHAR(64),
  UPPER_BOUND        BINARY_INTEGER,
  ELEM_TYPE_MOD      BINARY_INTEGER,
  ELEM_TYPE_UID      BINARY_INTEGER,
  ELEM_TYPE_NAME     VARCHAR(64),
  LENGTH             BINARY_INTEGER,
  PRECISION          BINARY_INTEGER,
  SCALE              BINARY_INTEGER,
  CHAR_SET           BINARY_INTEGER,
  ELEM_STORAGE       BINARY_INTEGER,
  NULLS_STORED       BINARY_INTEGER
)SYSTEM 1027 TABLESPACE SYSTEM
/
CREATE UNIQUE INDEX IDX_COLL_TYPE_001 ON SYS_COLL_TYPES(UID, TYPE_OID)
/
CREATE UNIQUE INDEX IDX_COLL_TYPE_002 ON SYS_COLL_TYPES(UID, TYPE_NAME)
/
ALTER SYSTEM LOAD DICTIONARY FOR SYS_COLL_TYPES
/

--01
CREATE TABLE SYS_TYPE_VERSIONS
(
  UID                BINARY_INTEGER,
  TYPE_OID           BINARY_BIGINT,
  TYPE_NAME          VARCHAR(64),
  TYPE_CODE          VARCHAR(8),
  STATUS             BINARY_INTEGER,
  LINE               BINARY_INTEGER,
  TEXT               VARCHAR(256),
  HASHCODE           BINARY_INTEGER,
  VERSION            BINARY_INTEGER
)SYSTEM 1028 TABLESPACE SYSTEM
/
CREATE INDEX IDX_TYPE_VER_001 ON SYS_TYPE_VERSIONS(UID, TYPE_OID, VERSION)
/
ALTER SYSTEM LOAD DICTIONARY FOR  SYS_TYPE_VERSIONS
/

--01
CREATE TABLE SYS_LIBRARIES
(
  USER#         BINARY_INTEGER         NOT  NULL,
  NAME          VARCHAR(64)            NOT  NULL,
  FILE_PATH     VARCHAR(256)           NOT  NULL,
  FLAGS         BINARY_INTEGER         NOT  NULL,
  STATUS        BINARY_INTEGER,
  AGENT         VARCHAR(256),
  LEAF_FILENAME VARCHAR(64),
  ORG_SCN       BINARY_BIGINT,
  CHG_SCN       BINARY_BIGINT
)SYSTEM 1029 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IDX_LIBRARY_001 ON SYS_LIBRARIES(USER#, NAME) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_LIBRARIES
/

--01
CREATE TABLE SYS_DDM
(
  USER#              BINARY_INTEGER,
  TABLE#             BINARY_INTEGER,
  COLUMN#            BINARY_INTEGER,
  RULE_NAME          VARCHAR(64),
  TYPE_NAME          VARCHAR(64),
  PARAM              VARCHAR(1024)
)SYSTEM 1030 TABLESPACE SYSTEM
/
CREATE INDEX IDX_DDM_001 ON SYS_DDM(USER#, TABLE#, COLUMN#)
/
CREATE INDEX IDX_DDM_002 ON SYS_DDM(USER#, TABLE#, RULE_NAME)
/
ALTER SYSTEM LOAD DICTIONARY FOR  SYS_DDM
/

--01
CREATE TABLE SYS_POLICIES
(
  OBJ_SCHEMA_ID     BINARY_INTEGER   NOT NULL,
  OBJ_NAME          VARCHAR(64)      NOT NULL,
  PNAME             VARCHAR(64)      NOT NULL,
  PF_SCHEMA         VARCHAR(64)      NOT NULL,
  PF_NAME           VARCHAR(128)     NOT NULL,
  STMT_TYPE         BINARY_INTEGER   DEFAULT 0 NOT NULL,
  PTYPE             BINARY_INTEGER   DEFAULT 0 NOT NULL,
  CHK_OPTION        BINARY_INTEGER   DEFAULT 0 NOT NULL,
  ENABLE            BINARY_INTEGER	 DEFAULT 0 NOT NULL,
  LONG_PREDICATE    BINARY_INTEGER   DEFAULT 0 NOT NULL
)SYSTEM 1031 TABLESPACE SYSTEM
/
CREATE UNIQUE INDEX IDX_SYS_POLICY_001 ON SYS_POLICIES(OBJ_SCHEMA_ID, OBJ_NAME, PNAME)
/
ALTER SYSTEM LOAD DICTIONARY FOR SYS_POLICIES
/

--01
CREATE TABLE SYS_USER_PRIVS
(
  UID           BINARY_INTEGER NOT NULL,
  GRANTOR       BINARY_INTEGER NOT NULL,
  GRANTEE       BINARY_INTEGER NOT NULL,
  PRIVILEGE     BINARY_INTEGER NOT NULL,
  OPTION        BINARY_INTEGER
) SYSTEM 1032 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_USER_PRIVS$_001 ON SYS_USER_PRIVS(UID, GRANTEE, PRIVILEGE)
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_USER_PRIVS
/

--01
CREATE TABLE SYS_CONSISTENT_HASH_STRATEGIES
(
  SLICE_COUNT      BINARY_INTEGER  NOT NULL,
  GROUP_COUNT      BINARY_INTEGER  NOT NULL,
  BUCKETS          BLOB
)SYSTEM 1033 TABLESPACE SYSTEM
/
CREATE UNIQUE INDEX IDX_SYS_CONSISTENT_HASH_STRATEGIES_001 ON SYS_CONSISTENT_HASH_STRATEGIES(SLICE_COUNT, GROUP_COUNT)
/
ALTER SYSTEM LOAD DICTIONARY FOR SYS_CONSISTENT_HASH_STRATEGIES
/

--02
CREATE TABLE SYS_TENANTS
(
  TENANT_ID          BINARY_INTEGER   NOT NULL,
  NAME               VARCHAR(32)      NOT NULL,
  DATA_SPACE#        BINARY_INTEGER   NOT NULL,
  SPACE_NUM          BINARY_INTEGER   NOT NULL,
  SPACE_BITMAP       RAW(256)         NOT NULL,
  CTIME              DATE             NOT NULL,
  OPTIONS            RAW(128)
)SYSTEM 1034 TABLESPACE SYSTEM
/
CREATE UNIQUE INDEX IDX_SYS_TENANT_001 ON SYS_TENANTS(TENANT_ID)
/
CREATE UNIQUE INDEX IDX_SYS_TENANT_002 ON SYS_TENANTS(NAME)
/
ALTER SYSTEM LOAD DICTIONARY FOR SYS_TENANTS
/

--01
CREATE TABLE SYS_INSTANCE_INFO
(
NAME			VARCHAR(64)		NOT NULL,
VALUE 			BINARY_BIGINT	NOT NULL
) SYSTEM 1035 TABLESPACE SYSTEM
/
CREATE UNIQUE INDEX IDX_SYS_INSTANCE_INFO_001 ON SYS_INSTANCE_INFO(NAME)
/
ALTER SYSTEM LOAD DICTIONARY FOR SYS_INSTANCE_INFO
/

--01
CREATE TABLE SYS_COMPRESS_OBJECTS
(
  ORG_SCN           BINARY_BIGINT       NOT   NULL,
  COMPRESS_ALGO     BINARY_INTEGER      NOT   NULL,
  OBJECT_TYPE       BINARY_INTEGER      NOT   NULL
) SYSTEM 1036 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_COMPRESS_001 ON SYS_COMPRESS_OBJECTS(ORG_SCN) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_COMPRESS_OBJECTS
/
--01
CREATE TABLE SYS_TEMP_HISTGRAM
(
  USER#         BINARY_INTEGER,
  TABLE#        BINARY_INTEGER,
  COL#          BINARY_INTEGER,
  BUCKET        VARCHAR(4000),
  ENDPOINT      BINARY_INTEGER,
  PART#         BINARY_INTEGER,
  EPVALUE       VARCHAR(1000),
  SPARE1        BINARY_BIGINT,
  SPARE2        BINARY_BIGINT,
  SPARE3        BINARY_BIGINT
) SYSTEM 1037 TABLESPACE SYSAUX
/

CREATE INDEX IX_TEMP_HIST_003 ON SYS_TEMP_HISTGRAM(USER#,TABLE#,COL#,PART#,ENDPOINT)
/

ALTER SYSTEM LOAD DICTIONARY FOR  SYS_TEMP_HISTGRAM
/
--01
CREATE TABLE SYS_TEMP_HISTGRAM_ABSTR
(
  USER#         BINARY_INTEGER,
  TAB#          BINARY_INTEGER,
  COL#          BINARY_INTEGER,
  BUCKET_NUM    BINARY_INTEGER,
  ROW_NUM       BINARY_INTEGER,
  NULL_NUM      BINARY_INTEGER,
  ANALYZE_TIME  DATE,
  MINVALUE      VARCHAR(4000),
  MAXVALUE      VARCHAR(4000),
  DIST_NUM      BINARY_INTEGER,
  DENSITY       BINARY_DOUBLE,
  SPARE1        BINARY_BIGINT,
  SPARE2        BINARY_BIGINT,
  SPARE3        BINARY_BIGINT,
  SPARE4        BINARY_BIGINT
) SYSTEM 1038 TABLESPACE SYSAUX
/

CREATE INDEX IX_TEMP_HIST_HEAD_002 ON SYS_TEMP_HISTGRAM_ABSTR(ANALYZE_TIME)
/

CREATE UNIQUE INDEX IX_TEMP_HIST_HEAD_003 ON SYS_TEMP_HISTGRAM_ABSTR(USER#,TAB#,COL#,SPARE1)
/

ALTER SYSTEM LOAD DICTIONARY FOR  SYS_TEMP_HISTGRAM_ABSTR
/

--01
CREATE TABLE SYS_TRIGGERS
(	
    OBJ#             BINARY_BIGINT          NOT NULL,       --OID
    TYPE#            BINARY_INTEGER         NOT NULL,       --0 after stmt, 1 after each row, 2 before state, 3 before each row, 4 instead of
    EVENT#           BINARY_INTEGER         NOT NULL,
    OBJECT_UID       BINARY_INTEGER         NOT NULL,
    BASEOBJECT       BINARY_BIGINT          NOT NULL,       --table oid, or view oid
    WHENCLAUSE       VARCHAR2(4000),                        --currently not supported
    ENABLED          BINARY_INTEGER         NOT NULL,
    FLAGS            BINARY_INTEGER         NOT NULL,       -- 0 TABLE, 1 VIEW, 2 PLSQL
    ACTIONLINENO     BINARY_INTEGER         NOT NULL,
    ACTIONCOLNO      BINARY_INTEGER         NOT NULL,
    SPARE1           VARCHAR2(128),
    SPARE2           VARCHAR2(128),
    SPARE3           NUMBER,
    SPARE4           NUMBER
) SYSTEM 1039 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IDX_SYS_TRIGGER_001 ON SYS_TRIGGERS(OBJ#) TABLESPACE SYSTEM
/

CREATE INDEX IDX_SYS_TRIGGER_002 ON SYS_TRIGGERS(OBJECT_UID, BASEOBJECT, OBJ#) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_TRIGGERS
/

--01
CREATE TABLE SYS_UPGRADE_RECORD
(
    TIME                  DATE                 NOT NULL,
    ACTION                VARCHAR(128)         NOT NULL,
    OLD_VERSION           VARCHAR(256)                 ,
    NEW_VERSION           VARCHAR(256)         NOT NULL
) SYSTEM 1040 TABLESPACE SYSTEM
/
CREATE UNIQUE INDEX IDX_SYS_UPGRADE_RECORD_001 ON SYS_UPGRADE_RECORD(TIME, ACTION)
/
ALTER SYSTEM LOAD DICTIONARY FOR SYS_UPGRADE_RECORD
/

--01
CREATE TABLE SYS_PROMOTE_RECORD
(
    TIME            DATE,
    TYPE            VARCHAR2(16),
    LOCAL_HOST      VARCHAR2(64),
    PEER_HOST       VARCHAR2(64)
) SYSTEM 1041 TABLESPACE SYSTEM
/

CREATE INDEX IX_SYS_PROMOTE_RECORD_001 ON SYS_PROMOTE_RECORD(TIME) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_PROMOTE_RECORD
/
--01
CREATE TABLE SYS_SPM
(
    SCHEMA           VARCHAR(64)           NOT NULL,
    SQL_ID           VARCHAR(10)           NOT NULL,
    SQL_SIGN         VARCHAR(32)           NOT NULL,
    SIGNATURE        VARCHAR(32),
    PLAN_SRC         BINARY_INTEGER        NOT NULL,
    STATUS           BINARY_INTEGER        NOT NULL,
    LAST_STATUS      BINARY_INTEGER        NOT NULL,
    CREATE_TIME      DATE                  NOT NULL,
    MODIFY_TIME      DATE                  NOT NULL,
    COST             NUMBER                NOT NULL,
    EXEC_TIME        BINARY_INTEGER        NOT NULL,
    EVOLUTION        BINARY_INTEGER        NOT NULL,
    PROF_NAME        VARCHAR(64),
    PROFILE          VARCHAR(4000),
    OUTLINE          CLOB
) SYSTEM 1042 TABLESPACE SYSTEM
/

CREATE INDEX IDX_SYS_SPM_001 ON SYS_SPM(SCHEMA, SQL_ID, SIGNATURE) TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IDX_SYS_SPM_002 ON SYS_SPM(PROF_NAME) TABLESPACE SYSTEM
/

CREATE INDEX IDX_SYS_SPM_003 ON SYS_SPM(SCHEMA, SQL_ID, SQL_SIGN) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_SPM
/
--01
CREATE TABLE SYS_SPM_SQLS
(
    SCHEMA           VARCHAR(64)           NOT NULL,
    SQL_ID           VARCHAR(10)           NOT NULL,
    SQL_SIGN         VARCHAR(32)           NOT NULL,
    CREATE_TIME      DATE                  NOT NULL,
    SQL_TEXT         CLOB
) SYSTEM 1043 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IDX_SYS_SPM_SQLS_001 ON SYS_SPM_SQLS(SCHEMA, SQL_ID, SQL_SIGN) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_SPM_SQLS
/

--01
CREATE TABLE SYS_GARBAGE_TABLES
(
  UID            BINARY_INTEGER       NOT   NULL,
  TAB_NAME       VARCHAR(64)          NOT   NULL
) SYSTEM 1044 TABLESPACE SYSTEM
/

CREATE UNIQUE INDEX IX_GARBAGE_TABLE_001 ON SYS_GARBAGE_TABLES(UID, TAB_NAME) TABLESPACE SYSTEM
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_GARBAGE_TABLES
/

--01
CREATE TABLE SYS_TABLEMETA_DIFF
(
    OBJECT_SCN          BINARY_BIGINT       NOT NULL,
    USER_NAME           VARCHAR(64 BYTE)    NOT NULL,
    OBJECT_NAME         VARCHAR(64 BYTE)    NOT NULL,
    USER_ID             BINARY_INTEGER      NOT NULL,
    TABLE_ID            BINARY_INTEGER      NOT NULL,
    OBJECT_ID           BINARY_INTEGER      NOT NULL,
    OBJECT_VERSION      BINARY_BIGINT       NOT NULL,
    DDL_TYPE            VARCHAR(64 BYTE)    NOT NULL,
    CHG_SCN             BINARY_BIGINT       NOT NULL,
    INVALID_SCN         BINARY_BIGINT       NOT NULL,
    OPTIONS             RAW(128),
    CONSTRAINT "PK_SYS_TABLEMETA_DIFF" PRIMARY KEY("OBJECT_SCN", "OBJECT_VERSION", "CHG_SCN")
) SYSTEM 1045 TABLESPACE SYSAUX
/

CREATE INDEX IX_DIC_DIFF ON SYS_TABLEMETA_DIFF (USER_ID, TABLE_ID)
TABLESPACE SYSAUX
/

CREATE INDEX IX_DEL_DIFF ON SYS_TABLEMETA_DIFF (OBJECT_SCN, OBJECT_VERSION, CHG_SCN, INVALID_SCN)
TABLESPACE SYSAUX
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_TABLEMETA_DIFF
/

--01
CREATE TABLE SYS_COLUMNMETA_HIS
(
    OBJECT_SCN          BINARY_BIGINT       NOT NULL,
    OBJECT_VERSION      BINARY_BIGINT       NOT NULL,
    USER_ID             BINARY_INTEGER      NOT NULL,
    TABLE_ID            BINARY_INTEGER      NOT NULL,
    OBJECT_ID           BINARY_INTEGER      NOT NULL,
    COLUMN_ID           BINARY_INTEGER      NOT NULL,
    COLUMN_NAME         VARCHAR(64 BYTE)    NOT NULL,
    PRIMARY             BOOLEAN             NOT NULL,
    CHANGED             BOOLEAN             NOT NULL,
    DATATYPE            BINARY_INTEGER      NOT NULL,
    BYTES               BINARY_INTEGER      NOT NULL,
    PRECISION           BINARY_INTEGER,
    SCALE               BINARY_INTEGER,
    NULLABLE            BINARY_INTEGER      NOT NULL,
    FLAGS               BINARY_INTEGER      NOT NULL,
    DEFAULT_TEXT        VARCHAR(1024 BYTE),
    OPTIONS             RAW(128),
    CONSTRAINT "PK_SYS_COLUMNMETA_HIS" PRIMARY KEY("OBJECT_SCN", "OBJECT_VERSION", "COLUMN_ID")
) SYSTEM 1046 TABLESPACE SYSAUX
/

CREATE INDEX IX_DIC_HIS ON SYS_COLUMNMETA_HIS (USER_ID, TABLE_ID)
TABLESPACE SYSAUX
/

ALTER SYSTEM LOAD DICTIONARY FOR SYS_COLUMNMETA_HIS
/
