drop table if exists person;
create table person(personcode int,personname varchar(20),addresscode int);
insert into person values(1,'小赵',1);
insert into person values(2,'小钱',2);
insert into person values(3,'赵四',3);
insert into person values(4,'孙晔',4);
insert into person values(5,'周瑜',6);
drop table if exists address;
create table address(addresscode int,addressname varchar(20));
insert into address values(1,'北京');
insert into address values(2,'上海');
insert into address values(3,'广州');
insert into address values(4,'深圳');
insert into address values(5,'上海');
select * from person per right join address ad on per.addresscode = ad.addresscode;
select * from person per right outer join address ad on per.addresscode = ad.addresscode;
drop table if exists person;
drop table if exists address;
